--Contains all text in English for the ATM display
local config = {}

config.AmountSelect = "Select amount"
config.Complete = "Transaction complete"
config.Frozen = "Account frozen"
config.LangSelect = "Select language"
config.OpSelect = "Select operation"
config.TapCard = "Tap bank card"
config.ViewBalance = "Account balance"

config.AmountPage = "Other"
config.BackPage = "Back"
config.BalancePage = "Balance"
config.WithdrawPage = "Withdraw"

config.AvailableBalance = "Available balance:"

config.CancelMistake = "In case of a mistake press Cancel."

config.MultipleLimit = "Multiples of ₲500."

config.InvalidInput = "Please try again with a different amount."
config.Overdraw = "Insufficient funds in account."
config.SuccessfulWithdraw = "Thank you for banking with us today."
config.Timeout = "Your session timed out due to inactivity."

return config