--Contains all text in Croatian for the ATM display
local config = {}

config.AmountSelect = "Odaberite iznos"
config.Complete = "Transakcija završena"
config.LangSelect = "Odaberite jezik"
config.OpSelect = "Odaberite transakciju"
config.TapCard = "Prislonite karticu"
config.ViewBalance = "Prikaz stanja računa"

config.AmountPage = "Drugi iznos"
config.BackPage = "Nazad"
config.BalancePage = "Stanje računa"
config.WithdrawPage = "Isplata"

config.AvailableBalance = "Raspoloživi isnos:"

config.CancelMistake = "U slučaju pogreške pritisnite Cancel."

config.MultipleLimit = "Iznos zaokružite na ₲500."

config.InvalidInput = "Pokušajte ponovo s drugim iznosom."
config.Overdraw = "Nedostatna sredstva na računu."
config.SuccessfulWithdraw = "Hvala što ste koristili naš bankomat."
config.Timeout = "Transakcija je istekla zbog neaktivnosti."

return config