--Contains all text in Serbian for the ATM display
local config = {}

config.AmountSelect = "Одаберите износ"
config.Complete = "Трансакција завршена"
config.LangSelect = "Одаберите језик"
config.OpSelect = "Одаберите трансакцију"
config.TapCard = "Прислоните картицу"
config.ViewBalance = "Приказ стања рачуна"

config.AmountPage = "Други износ"
config.BackPage = "Назад"
config.BalancePage = "Стање рачуна"
config.WithdrawPage = "Исплата"

config.AvailableBalance = "Расположиви износ:"

config.CancelMistake = "У случају погрешке притисните Cancel."

config.MultipleLimit = "Износ заокружите на ₲500."

config.InvalidInput = "Покушајте поново с другим исносом."
config.Overdraw = "Недостатна средства на рачуну."
config.SuccessfulWithdraw = "Хвала што сте користили наш банкомат."
config.Timeout = "Трансакција је истекла због неактивности."

return config