--Contains all text in Valakese (Bloxellian) for the ATM display
local config = {}

config.AmountSelect = "Кохлума хелу"
config.Complete = "Хана е пиха"
config.LangSelect = "Кохлума олеха"
config.OpSelect = "Кохлума хана"
config.TapCard = "Хуплума калта'панка'поа"
config.ViewBalance = "Хелу ли лахуно"

config.AmountPage = "Оку"
config.BackPage = "Аватлуме"
config.BalancePage = "Хелу"
config.WithdrawPage = "Лавлума"

config.AvailableBalance = "Хелу'лову:"

config.CancelMistake = "Лиа а хева’кухи’виа хуплума Cancel."

config.MultipleLimit = "Хелуво маи ₲500."

config.InvalidInput = "Пловлума к'толума ме хелу'оку."
config.Overdraw = "Хелу ли лахуно е к'оле лаву."
config.SuccessfulWithdraw = "Ево лофаи и мо и алка ле панку'ту лало ла'та."
config.Timeout = "Хана'ла пихке ми мули маи хана'ола."

return config