--All information regarding articles of clothing
local config = {}

config.ActiveShooter = {
    DisplayName = "\"Active Shooter\" Basketball Tee";
    Type = "Shirt";
    Template = "rbxassetid://11237264417";
}

config.AmiriJeansLouboutins = {
    DisplayName = "Ripped Amiri Jeans and White Louboutins";
    RobloxId = 3217363998;
    Type = "Pants";
    Template = "rbxassetid://3217363973";
}

config.ArrivalsBottom = {
    DisplayName = "Arrivals Jumpsuit Pants";
    Type = "Pants";
    Template = "rbxassetid://16195395926";
}

config.ArrivalsTop = {
    DisplayName = "Arrivals Jumpsuit";
    Type = "Shirt";
    Template = "rbxassetid://16195396953";
}

config.AshBalmainTee = {
    DisplayName = "Ash Balmain T-Shirt";
    RobloxId = 5197124823;
    Type = "Shirt";
    Template = "rbxassetid://5197124803";
}

config.BeautifulYou = {
    DisplayName = "\"Beautiful You\" Jeans";
    Type = "Pants";
    Template = "rbxassetid://398634485";
}

config.Beige3PieceBottom = {
    DisplayName = "Beige 3 Piece Suit";
    RobloxId = 125174922;
    Type = "Pants";
    Template = "rbxassetid://125174921";
}

config.Beige3PieceTop = {
    DisplayName = "Beige 3 Piece Suit";
    RobloxId = 125174898;
    Type = "Shirt";
    Template = "rbxassetid://125174897";
}

config.BeigeDressPants = {
    DisplayName = "Beige Dress Pants";
    RobloxId = 9339134197;
    Type = "Pants";
    Template = "rbxassetid://9339134184";
}

config.BeigeSweater = {
    DisplayName = "Beige Sweater";
    RobloxId = 9065250423;
    Type = "Shirt";
    Template = "rbxassetid://9065250409";
}

config.BikerJeansBlackYeezys = {
    DisplayName = "Biker Jeans with Black Yeezy Boost 350s";
    RobloxId = 3397114451;
    Type = "Pants";
    Template = "rbxassetid://3397114431";
}

config.BikerJeansJordan11s = {
    DisplayName = "Biker Jeans with Gucci Belt and Jordan 11s";
    RobloxId = 5216691299;
    Type = "Pants";
    Template = "rbxassetid://5216691276";
}

config.Black2ButtonBottom = {
    DisplayName = "Black 2 Buttoned Suit";
    RobloxId = 6006586130;
    Type = "Pants";
    Template = "rbxassetid://6006586093";
}

config.Black2ButtonTop = {
    DisplayName = "Black 2 Buttoned Suit";
    RobloxId = 6006584500;
    Type = "Shirt";
    Template = "rbxassetid://6006584470";
}

config.Black6Sweatpants = {
    DisplayName = "Black 6-Stripe Sweatpants";
    RobloxId = 16906883086;
    Type = "Pants";
    Template = "rbxassetid://16906883046";
}

config.Black6Tracksuit = {
    DisplayName = "Black 6-Stripe Tracksuit Jacket";
    RobloxId = 16906874964;
    Type = "Shirt";
    Template = "rbxassetid://16906874925";
}

config.BlackClassicBusinessBottom = {
    DisplayName = "Black Classic Business Suit";
    RobloxId = 138981719;
    Type = "Pants";
    Template = "rbxassetid://138981718";
}

config.BlackClassicBusinessTop = {
    DisplayName = "Black Classic Business Suit";
    RobloxId = 138632986;
    Type = "Shirt";
    Template = "rbxassetid://138632985";
}

config.BlackClassicFitBottom = {
    DisplayName = "Black Classic Fitted Suit";
    RobloxId = 6332548864;
    Type = "Pants";
    Template = "rbxassetid://6332548832";
}

config.BlackClassicFitTop = {
    DisplayName = "Black Classic Fitted Suit";
    RobloxId = 6332545861;
    Type = "Shirt";
    Template = "rbxassetid://6332545824";
}

config.BlackDressPants = {
    DisplayName = "Black Dress Pants";
    RobloxId = 8411502643;
    Type = "Pants";
    Template = "rbxassetid://8411502630";
}

config.BlackDressTrousers = {
    DisplayName = "Black Dress Trousers";
    RobloxId = 5944855603;
    Type = "Pants";
    Template = "rbxassetid://5944855553";
}

config.BlackDressShirt = {
    DisplayName = "Black Dress Shirt";
    RobloxId = 5944853050;
    Type = "Shirt";
    Template = "rbxassetid://5944853014";
}

config.BlackFurTrenchBottom = {
    DisplayName = "Black Fur Trench Coat";
    RobloxId = 8572655806;
    Type = "Pants";
    Template = "rbxassetid://8572655792";
}

config.BlackFurTrenchTop = {
    DisplayName = "Black Fur Trench Coat";
    RobloxId = 8572650670;
    Type = "Shirt";
    Template = "rbxassetid://8572650647";
}

config.BlackGoldSuitBottom = {
    DisplayName = "Black & Gold Suit";
    RobloxId = 11854008675;
    Type = "Pants";
    Template = "rbxassetid://11854008657";
}

config.BlackGoldSuitTop = {
    DisplayName = "Black & Gold Suit";
    RobloxId = 11854025062;
    Type = "Shirt";
    Template = "rbxassetid://11854025013";
}

config.BlackJeans = {
    DisplayName = "Black Jeans";
    Type = "Pants";
    Template = "rbxassetid://382537568";
}

config.BlackJeansSneakers = {
    DisplayName = "Black Jeans with Sneakers";
    Type = "Pants";
    Template = "rbxassetid://382538502";
}

config.BlackJeansWhiteShoes = {
    DisplayName = "Black Jeans with White Shoes";
    Type = "Pants";
    Template = "rbxassetid://398633811";
}

config.BlackLabel3PieceBottom = {
    DisplayName = "Black Label 3 Piece Suit";
    RobloxId = 2230026455;
    Type = "Pants";
    Template = "rbxassetid://2230026439";
}

config.BlackLabel3PieceTop = {
    DisplayName = "Black Label 3 Piece Suit";
    RobloxId = 2229990167;
    Type = "Shirt";
    Template = "rbxassetid://2229990136";
}

config.BlackLabelBlazerBottom = {
    DisplayName = "Black Label Blazer";
    RobloxId = 2230027031;
    Type = "Pants";
    Template = "rbxassetid://2230027024";
}

config.BlackLabelBlazerTop = {
    DisplayName = "Black Label Blazer";
    RobloxId = 2229991662;
    Type = "Shirt";
    Template = "rbxassetid://2229991655";
}

config.BlackLabelBottom = {
    DisplayName = "Black Label Open Suit";
    RobloxId = 2230030258;
    Type = "Pants";
    Template = "rbxassetid://2230030242";
}

config.BlackLabelBowtieBottom = {
    DisplayName = "Black Label Suit with Bowtie";
    RobloxId = 2230031675;
    Type = "Pants";
    Template = "rbxassetid://2230033138";
}

config.BlackLabelBowtieTop = {
    DisplayName = "Black Label Suit with Bowtie";
    RobloxId = 2230002321;
    Type = "Shirt";
    Template = "rbxassetid://2230005001";
}

config.BlackLabelPeacoatBottom = {
    DisplayName = "Black Label Peacoat";
    RobloxId = 2230030881;
    Type = "Pants";
    Template = "rbxassetid://2230030872";
}

config.BlackLabelPeacoatTop = {
    DisplayName = "Black Label Peacoat";
    RobloxId = 2229998911;
    Type = "Shirt";
    Template = "rbxassetid://2229998900";
}

config.BlackLabelTop = {
    DisplayName = "Black Label Open Suit";
    RobloxId = 2229996670;
    Type = "Shirt";
    Template = "rbxassetid://2229996662";
}

config.BlackLabelTrenchBottom = {
    DisplayName = "Black Label Trench Coat";
    RobloxId = 2230032494;
    Type = "Pants";
    Template = "rbxassetid://2230033138";
}

config.BlackLabelTrenchTop = {
    DisplayName = "Black Label Trench Coat";
    RobloxId = 2230005005;
    Type = "Shirt";
    Template = "rbxassetid://2230005001";
}

config.BlackLabelTuxBottom = {
    DisplayName = "Black Label Tuxedo";
    RobloxId = 2230033156;
    Type = "Pants";
    Template = "rbxassetid://2230033138";
}

config.BlackLabelTuxTop = {
    DisplayName = "Black Label Tuxedo";
    RobloxId = 2230005888;
    Type = "Shirt";
    Template = "rbxassetid://2230005880";
}

config.BlackLabelVestBottom = {
    DisplayName = "Black Label Suit with Vest";
    RobloxId = 2230029475;
    Type = "Pants";
    Template = "rbxassetid://2230029468";
}

config.BlackLabelVestTop = {
    DisplayName = "Black Label Suit with Vest";
    RobloxId = 2229995774;
    Type = "Shirt";
    Template = "rbxassetid://2229995766";
}

config.BlackLeggingsWhiteSneakers = {
    DisplayName = "Black Leggings with White Sneakers";
    RobloxId = 7864346252;
    Type = "Pants";
    Template = "rbxassetid://7864346240";
}

config.BlackLeisureBottom = {
    DisplayName = "Black Leisure Suit";
    RobloxId = 136506010;
    Type = "Pants";
    Template = "rbxassetid://136506009";
}

config.BlackLeisureTop = {
    DisplayName = "Black Leisure Suit";
    RobloxId = 136505906;
    Type = "Shirt";
    Template = "rbxassetid://136505905";
}

config.BlackLevisJordan4s = {
    DisplayName = "Black Levi Jeans with Jordan 4s";
    RobloxId = 12779282912;
    Type = "Pants";
    Template = "rbxassetid://12779282887";
}

config.BlackNorthFacePufferXGrayHoodie = {
    DisplayName = "Black North Face Puffer and Gray Hoodie";
    RobloxId = 5681306135;
    Type = "Shirt";
    Template = "rbxassetid://5681306116";
}

config.BlackPants = {
    DisplayName = "Black Pants";
    RobloxId = 126901099;
    Type = "Pants";
    Template = "rbxassetid://126901098";
}

config.BlackPuffer = {
    DisplayName = "Black Puffer Jacket";
    RobloxId = 7392770834;
    Type = "Shirt";
    Template = "rbxassetid://7392770829";
}

config.BlackSamuraiPants = {
    DisplayName = "Black Samurai Pants";
    RobloxId = 5261932283;
    Type = "Pants";
    Template = "rbxassetid://5261932247";
}

config.BlackSupremeXChampion = {
    DisplayName = "Black Supreme X Champion Hoodie";
    RobloxId = 5643100607;
    Type = "Shirt";
    Template = "rbxassetid://5643100589";
}

config.BlackTee = {
    DisplayName = "Black Tee";
    RobloxId = 789336534;
    Type = "Shirt";
    Template = "rbxassetid://789336525";
}

config.BlackWhiteFloralDress = {
    DisplayName = "Black and White Floral Dress";
    RobloxId = 149110668;
    Type = "Pants";
    Template = "rbxassetid://149110666";
}

config.BLoxTee = {
    DisplayName = "B-Lox Tee";
    RobloxId = 16845243420;
    Type = "Shirt";
    Template = "rbxassetid://16845243341";
}

config.BlueBikerJeansJordan4s = {
    DisplayName = "Blue Biker Jeans with Jordan 4s 'Motorsports'";
    RobloxId = 5642892731;
    Type = "Pants";
    Template = "rbxassetid://5642892714";
}

config.BlueBlackMotorcycle = {
    DisplayName = "Blue and Black Motorcycle Shirt";
    Type = "Shirt";
    Template = "rbxassetid://144076357";
}

config.BlueStonewashJeans = {
    DisplayName = "Blue Stonewash Jeans";
    RobloxId = 13782399222;
    Type = "Pants";
    Template = "rbxassetid://13782399197";
}

config.BlueTopShortShorts = {
    DisplayName = "Blue Top with Short Shorts";
    RobloxId = 152907860;
    Type = "Pants";
    Template = "rbxassetid://152907859";
}

config.Brown2ButtonBottom = {
    DisplayName = "Brown 2 Buttoned Suit";
    RobloxId = 6185123116;
    Type = "Pants";
    Template = "rbxassetid://6185123064";
}

config.Brown2ButtonTop = {
    DisplayName = "Brown 2 Buttoned Suit";
    RobloxId = 6185122837;
    Type = "Shirt";
    Template = "rbxassetid://6185122784";
}

config.BrownCasualPants = {
    DisplayName = "Brown Casual Pants";
    RobloxId = 414289828;
    Type = "Pants";
    Template = "rbxassetid://414289827";
}

config.BusyGaming = {
    DisplayName = "\"Busy Gaming\" Tee";
    RobloxId = 10095171700;
    Type = "Shirt";
    Template = "rbxassetid://10095171684";
}

config.CasualBlackJeans = {
    DisplayName = "Black Jeans";
    Type = "Pants";
    Template = "rbxassetid://6992375414";
}

config.ColdestTee = {
    DisplayName = "\"Coldest\" Emoji Tee";
    Type = "Shirt";
    Template = "rbxassetid://17763626567";
}

config.DarkGreenJeans = {
    DisplayName = "Dark Green Jeans";
    Type = "Pants";
    Template = "rbxassetid://144076759";
}

config.DDRTracksuitBottom = {
    DisplayName = "Adidas 1970s DDR Tracksuit Pants";
    RobloxId = 7542235070;
    Type = "Pants";
    Template = "rbxassetid://7542235068";
}

config.DDRTracksuitTop = {
    DisplayName = "Adidas 1970s DDR Tracksuit Top";
    RobloxId = 7542236299;
    Type = "Shirt";
    Template = "rbxassetid://7542236295";
}

config.DenimJacketWhiteHoodie = {
    DisplayName = "Denim Jacket with White Hoodie";
    Type = "Shirt";
    Template = "rbxassetid://398633582";
}

config.Dragon3PieceBottom = {
    DisplayName = "Dragon Patterned 3 Piece Suit";
    RobloxId = 6526520102;
    Type = "Pants";
    Template = "rbxassetid://6526520079";
}

config.Dragon3PieceTop = {
    DisplayName = "Dragon Patterned 3 Piece Suit";
    RobloxId = 6526518332;
    Type = "Shirt";
    Template = "rbxassetid://6526518264";
}

config.DragonButtonDown = {
    DisplayName = "Dragon Pattern Button Down";
    RobloxId = 6416771124;
    Type = "Shirt";
    Template = "rbxassetid://6416771024";
}

config.Gray2ButtonBottom = {
    DisplayName = "Gray 2 Buttoned Suit";
    RobloxId = 6185123662;
    Type = "Pants";
    Template = "rbxassetid://6185123625";
}

config.Gray2ButtonTop = {
    DisplayName = "Gray 2 Buttoned Suit";
    RobloxId = 6185123386;
    Type = "Shirt";
    Template = "rbxassetid://6185123349";
}

config.GrayBlazerTurtleneckBottom = {
    DisplayName = "Gray Blazer with Turtleneck";
    RobloxId = 12427431453;
    Type = "Pants";
    Template = "rbxassetid://12427431438";
}

config.GrayBlazerTurtleneckTop = {
    DisplayName = "Gray Blazer with Turtleneck";
    RobloxId = 12427426362;
    Type = "Shirt";
    Template = "rbxassetid://12427426358";
}

config.GrayDressPants = {
    DisplayName = "Gray Dress Pants";
    RobloxId = 6346382546;
    Type = "Pants";
    Template = "rbxassetid://6346382525";
}

config.GrayPlaidSkirt = {
    DisplayName = "Gray Plaid Skirt";
    RobloxId = 9054845078;
    Type = "Pants";
    Template = "rbxassetid://9054845037";
}

config.GrayShirtDenimJacket = {
    DisplayName = "Gray Striped Shirt with Denim Jacket";
    Type = "Shirt";
    Template = "rbxassetid://144076435";
}

config.GrayStonewashJeans = {
    DisplayName = "Gray Stonewash Jeans";
    RobloxId = 16113272825;
    Type = "Pants";
    Template = "rbxassetid://16113272394";
}

config.GreenFestiveGown = {
    DisplayName = "Green Festive Gown";
    RobloxId = 8219800686;
    Type = "Pants";
    Template = "rbxassetid://8219800662";
}

config.GreenFlannel = {
    DisplayName = "Green Flannel";
    RobloxId = 9893217968;
    Type = "Shirt";
    Template = "rbxassetid://9893217960";
}

config.GreenJersey = {
    DisplayName = "Green Jersey";
    Type = "Shirt";
    Template = "rbxassetid://382538058";
}

config.GreenPants = {
    DisplayName = "Green Pants";
    RobloxId = 325498659;
    Type = "Pants";
    Template = "rbxassetid://325498658";
}

config.GreenPatagoniaCrewneck = {
    DisplayName = "Green Patagonia Crewneck";
    RobloxId = 5944082083;
    Type = "Shirt";
    Template = "rbxassetid://5944082059";
}

config.GreenPlaidShirt = {
    DisplayName = "Green Plaid Shirt";
    RobloxId = 434144973;
    Type = "Shirt";
    Template = "rbxassetid://434144972";
}

config.GrimyWhiteTanktop = {
    DisplayName = "Grimy White Tanktop";
    RobloxId = 16844631751;
    Type = "Shirt";
    Template = "rbxassetid://16844631696";
}

config.GuitarTeeBlackJacket = {
    DisplayName = "Guitar Tee with Black Jacket";
    Type = "Shirt";
    Template = "rbxassetid://4047884003";
}

config.Herringbone3PieceBottom = {
    DisplayName = "Herringbone 3 Piece Suit";
    RobloxId = 6338068132;
    Type = "Pants";
    Template = "rbxassetid://6338068113";
}

config.Herringbone3PieceTop = {
    DisplayName = "Herringbone 3 Piece Suit";
    RobloxId = 6338065992;
    Type = "Shirt";
    Template = "rbxassetid://6338065976";
}

config.JeanShorts = {
    DisplayName = "Jean Shorts";
    Type = "Pants";
    Template = "rbxassetid://382537805";
}

config.JeanShortsWhiteShoes = {
    DisplayName = "Jean Shorts with White Shoes";
    Type = "Pants";
    Template = "rbxassetid://382537949";
}

config.KhakiChinoBlueConverse = {
    DisplayName = "Khaki Chinos with Blue Converse";
    RobloxId = 155154447;
    Type = "Pants";
    Template = "rbxassetid://155154446";
}

config.KhakiPants = {
    DisplayName = "Khaki Textured Pants";
    RobloxId = 220200985;
    Type = "Pants";
    Template = "rbxassetid://220200984";
}

config.KhakiPantsBlackSneakers = {
    DisplayName = "Khaki Pants with Black Sneakers";
    RobloxId = 191018108;
    Type = "Pants";
    Template = "rbxassetid://191018107";
}

config.KhakiPantsConverse = {
    DisplayName = "Khaki Pants with Black Converse";
    RobloxId = 158324370;
    Type = "Pants";
    Template = "rbxassetid://158324369";
}

config.LacedTopCuffs = {
    DisplayName = "Laced Top with Cuffs";
    RobloxId = 9054850303;
    Type = "Shirt";
    Template = "rbxassetid://9054850291";
}

config.LibertyDeathTee = {
    DisplayName = "\"Liberty or Death\" Patriotic Tee";
    Type = "Shirt";
    Template = "rbxassetid://17763697277";
}

config.LoveMinion = {
    DisplayName = "I <3 Minion Tee";
    Type = "Shirt";
    Template = "rbxassetid://8950155096";
}

config.LovePizza = {
    DisplayName = "I <3 Pizza Shirt";
    Type = "Shirt";
    Template = "rbxassetid://382537084";
}

config.LovePurchase = {
    DisplayName = "I <3 eBay Tee";
    RobloxId = 15601352375;
    Type = "Shirt";
    Template = "rbxassetid://15601352347";
}

config.MIABottom = {
    DisplayName = "MIA Uniform Pants";
    Type = "Pants";
    Template = "rbxassetid://18322976351";
}

config.MIACadet = {
    DisplayName = "MIA Cadet Uniform";
    Type = "Shirt";
    Template = "rbxassetid://18323134589";
}

config.MIACaptain = {
    DisplayName = "MIA Captain Uniform";
    Type = "Shirt";
    Template = "rbxassetid://18323134394";
}

config.MIAColonel = {
    DisplayName = "MIA Colonel General Uniform";
    Type = "Shirt";
    Template = "rbxassetid://18323134167";
}

config.MIADMinister= {
    DisplayName = "MIA Deputy Minister Uniform";
    Type = "Shirt";
    Template = "rbxassetid://18323133933";
}

config.MIAMinister = {
    DisplayName = "MIA Minister Uniform";
    Type = "Shirt";
    Template = "rbxassetid://18323133601";
}

config.MIALt = {
    DisplayName = "MIA Lieutenant Uniform";
    Type = "Shirt";
    Template = "rbxassetid://18323133315";
}

config.MIAOfficer = {
    DisplayName = "MIA Officer Uniform";
    Type = "Shirt";
    Template = "rbxassetid://18323133080";
}

config.MIASgt = {
    DisplayName = "MIA Sergeant Uniform";
    Type = "Shirt";
    Template = "rbxassetid://18323132427";
}

config.Navy2ButtonBottom = {
    DisplayName = "Navy 2 Buttoned Suit";
    RobloxId = 6185129067;
    Type = "Pants";
    Template = "rbxassetid://6185129021";
}

config.Navy2ButtonTop = {
    DisplayName = "Navy 2 Buttoned Suit";
    RobloxId = 6185128572;
    Type = "Shirt";
    Template = "rbxassetid://6185128529";
}

config.NBAFBottom = {
    DisplayName = "NBAF Uniform Bottom";
    Type = "Pants";
    Template = "rbxassetid://2943257446";
}

config.NBAFTop = {
    DisplayName = "NBAF Uniform Top";
    Type = "Shirt";
    Template = "rbxassetid://6846011258";
}

config.NBCFBottom = {
    DisplayName = "NBCF Jumpsuit Pants";
    Type = "Pants";
    Template = "rbxassetid://18330601568";
}

config.NBCFTop = {
    DisplayName = "NBCF Jumpsuit";
    Type = "Shirt";
    Template = "rbxassetid://18330600618";
}

config.NukingLegal = {
    DisplayName = "\"Nuking is Legal\" Tee";
    RobloxId = 14808607797;
    Type = "Shirt";
    Template = "rbxassetid://14808607758";
}

config.OffWhiteVloneBlackTee = {
    DisplayName = "Off-White Vlone Black T-shirt";
    RobloxId = 5642951658;
    Type = "Shirt";
    Template = "rbxassetid://5642951635";
}

config.OffWhiteVloneWhiteTee = {
    DisplayName = "Off-White Vlone White T-shirt";
    RobloxId = 5642947208;
    Type = "Shirt";
    Template = "rbxassetid://5642947192";
}

config.PastelTopGrayJacket = {
    DisplayName = "Pastel Starburst Top with Gray Jacket";
    Type = "Shirt";
    Template = "rbxassetid://398634294";
}

config.PaycheckBlackHoodie = {
    DisplayName = "Paycheck Gang Black Hoodie";
    Type = "Shirt";
    Template = "rbxassetid://8716149899";
}

config.PaycheckBlackHoodiePurple = {
    DisplayName = "Paycheck Gang Black Hoodie with Purple Text";
    Type = "Shirt";
    Template = "rbxassetid://16534686155";
}

config.PaycheckWhiteHoodie = {
    DisplayName = "Paycheck Gang White Hoodie";
    Type = "Shirt";
    Template = "rbxassetid://16671732178";
}

config.PaycheckWhiteHoodiePurple = {
    DisplayName = "Paycheck Gang White Hoodie with Purple Text";
    Type = "Shirt";
    Template = "rbxassetid://16671726418";
}

config.PinkArgyle = {
    DisplayName = "Pink Argyle Sweater";
    RobloxId = 132611094;
    Type = "Shirt";
    Template = "rbxassetid://132611093";
}

config.PinkFlamingoButtonUp = {
    DisplayName = "Pink Flamingo Button Up";
    RobloxId = 2155194423;
    Type = "Shirt";
    Template = "rbxassetid://2155194400";
}

config.PinkFormalShirt = {
    DisplayName = "Pink Formal Shirt";
    RobloxId = 147482692;
    Type = "Shirt";
    Template = "rbxassetid://147482690";
}

config.PinkShirtNavyVest = {
    DisplayName = "Pink Shirt with Navy Pinstripe Vest";
    RobloxId = 897197403;
    Type = "Shirt";
    Template = "rbxassetid://897197399";
}

config.PinkSparkleGown = {
    DisplayName = "Pink Sparkle Gown";
    RobloxId = 6418491386;
    Type = "Pants";
    Template = "rbxassetid://6418491365";
}

config.PinkJeans = {
    DisplayName = "Pink Jeans";
    Type = "Pants";
    Template = "rbxassetid://144076511";
}

config.PoliceBalaclava = {
    AttachesTo = "Head";
    DisplayName = "Police Balaclava";
    HidesHair = true;
    Mask = true;
    Type = "Accessory";
}

config.PoliceVest = {
    AttachesTo = "Torso";
    DisplayName = "Police Vest";
    Type = "Accessory";
}

config.PresidentBottom = {
    DisplayName = "President of North Bloxell Uniform Pants";
    Type = "Pants";
    Template = "rbxassetid://923217146";
}

config.PresidentTop = {
    DisplayName = "President of North Bloxell Uniform Jacket";
    Type = "Shirt";
    Template = "rbxassetid://4896293816";
}

config.PumpIt = {
    DisplayName = "\"Pump It\" Tee";
    RobloxId = 15514090135;
    Type = "Shirt";
    Template = "rbxassetid://15514090111";
}

config.PurplePuffer = {
    DisplayName = "Purple Puffer Jacket";
    RobloxId = 8760456904;
    Type = "Shirt";
    Template = "rbxassetid://8760456889";
}

config.PurpleTealTop = {
    DisplayName = "Purple and Teal Top";
    Type = "Shirt";
    Template = "rbxassetid://4047886039";
}

config.RedSparkleDress = {
    DisplayName = "Red Sparkle Dress";
    RobloxId = 143994583;
    Type = "Pants";
    Template = "rbxassetid://143994582";
}

config.RippedJeansWhiteVans = {
    DisplayName = "Ripped Biker Jeans with White Vans";
    RobloxId = 5642956980;
    Type = "Pants";
    Template = "rbxassetid://5642956954";
}

config.SanitationBottom = {
    DisplayName = "Sanitation Services Bottom";
    Type = "Pants";
    Template = "rbxassetid://17796878112";
}

config.SanitationTop = {
    DisplayName = "Sanitation Services Top";
    Type = "Shirt";
    Template = "rbxassetid://17796843710";
}

config.Tan3PieceBottom = {
    DisplayName = "Tan 3 Piece Suit";
    RobloxId = 5355229775;
    Type = "Pants";
    Template = "rbxassetid://5355229748";
}

config.Tan3PieceTop = {
    DisplayName = "Tan 3 Piece Suit";
    RobloxId = 5355226307;
    Type = "Shirt";
    Template = "rbxassetid://5355226221";
}

config.TannedLeatherJacket = {
    DisplayName = "Tanned Leather Jacket";
    RobloxId = 149622149;
    Type = "Shirt";
    Template = "rbxassetid://149622148";
}

config.TrueHero = {
    DisplayName = "\"True Hero\" Tee";
    RobloxId = 15995800832;
    Type = "Shirt";
    Template = "rbxassetid://15995800810";
}

config.TrueJeansJordan11s = {
    DisplayName = "True Religion Biker Jeans with Louis Vuitton Belt and Jordan 11s";
    RobloxId = 5216503181;
    Type = "Pants";
    Template = "rbxassetid://5216503165";
}

config.WhiteBalenciagaTee = {
    DisplayName = "White Balenciaga T-Shirt";
    RobloxId = 5192338848;
    Type = "Shirt";
    Template = "rbxassetid://5192338833";
}

config.WatchedBIOTee = {
    DisplayName = "\"I'm Being Watched by the BIO\" Tee";
    Type = "Shirt";
    Template = "rbxassetid://17763564926";
}

config.WhiteDressBlueVest = {
    DisplayName = "White Dress Shirt with Blue Vest";
    RobloxId = 132611147;
    Type = "Shirt";
    Template = "rbxassetid://132611146";
}

config.WhiteDressHarness = {
    DisplayName = "White Dress Shirt with Harness";
    RobloxId = 6346348833;
    Type = "Shirt";
    Template = "rbxassetid://6346348809";
}

config.WhiteGoldSuitBottom = {
    DisplayName = "White and Gold Suit with Purple Vest";
    RobloxId = 6350208708;
    Type = "Pants";
    Template = "rbxassetid://6350208648";
}

config.WhiteGoldSuitTop = {
    DisplayName = "White and Gold Suit with Purple Vest";
    RobloxId = 6350204598;
    Type = "Shirt";
    Template = "rbxassetid://6350204545";
}

config.WhiteOffShoulderTop = {
    DisplayName = "White Off Shoulder Top";
    RobloxId = 981061862;
    Type = "Shirt";
    Template = "rbxassetid://981061837";
}

config.WhiteRomaniaTee = {
    DisplayName = "White Romania T-Shirt";
    RobloxId = 11459157678;
    Type = "Shirt";
    Template = "rbxassetid://11459157661";
}

config.WhiteTanktop = {
    DisplayName = "White Tanktop";
    RobloxId = 16844668728;
    Type = "Shirt";
    Template = "rbxassetid://16844668658";
}

config.WhiteTee = {
    DisplayName = "White Tee";
    RobloxId = 13661214042;
    Type = "Shirt";
    Template = "rbxassetid://13661214025";
}

config.WhiteUnderArmorTee = {
    DisplayName = "White Under Armor T-Shirt";
    RobloxId = 13306957091;
    Type = "Shirt";
    Template = "rbxassetid://13306957058";
}

config.CITIZEN_DEFAULT_SHIRT = config.WhiteTanktop
config.CITIZEN_DEFAULT_PANTS = config.ArrivalsBottom

config.IMMIGRANT_DEFAULT_SHIRT = config.ArrivalsTop
config.IMMIGRANT_DEFAULT_PANTS = config.ArrivalsBottom

return config