--This script contains keys for all sound IDs, in this way, sound IDs are easier to replace as they only have to be changed in one location
local config = {}

config.Airsoft = "rbxassetid://5707240744"

config.AKMagIn = "rbxassetid://4681157223"
config.AKMagOut = "rbxassetid://4681158033"

config.Alert = "rbxassetid://138221067"
config.AlertRocketENG = "rbxassetid://17103061719"
config.AlertRocketVLK = "rbxassetid://17103005942"
config.AllClearENG = "rbxassetid://17103223988"
config.AllClearVLK = "rbxassetid://17103303938"

config.ATMBeep = "rbxassetid://1283290053"
config.ATMDispense = "rbxassetid://9114349040"

config.BarbedWire = "rbxassetid://17261343458"

config.BlindsToggle = "rbxassetid://9120402790"

config.BulletHit = "rbxassetid://240891292"
config.BulletHitBrick = "rbxassetid://7158347304"
config.BulletHitConcrete = "rbxassetid://7158347304"
config.BulletHitCorrodedMetal = "rbxassetid://4072627278"
config.BulletHitDiamondPlate = "rbxassetid://4072627278"
config.BulletHitGlass = "rbxassetid://7140152893"
config.BulletHitHumanoid = "rbxassetid://255661850"
config.BulletHitMetal = "rbxassetid://4072627278"
config.BulletHitWood = "rbxassetid://8542224819"
config.BulletHitWoodPlanks = "rbxassetid://8542224819"
config.BulletWhiz = "rbxassetid://9113634444"

config.DoorClose = "rbxassetid://7038967181"
config.DoorOpen = "rbxassetid://157167203"
config.DoorLocked = "rbxassetid://134969396"

config.Drink = "rbxassetid://9114172109"
config.SoftChew = "rbxassetid://179303694"

config.EmergencyENG = "rbxassetid://17189432413"
config.EmergencyVLK = "rbxassetid://17189436840"
config.EmergencyLiftedENG = "rbxassetid://17189415062"
config.EmergencyLiftedVLK = "rbxassetid://17189428491"

config.Explosion = "rbxassetid://2648563122"
config.ExplosionFar = "rbxassetid://180199774"

config.FallDamage = "rbxassetid://9113480915"
config.WilhelmScream = "rbxassetid://160718677"

config.FireSelector = "rbxassetid://484110242"

config.Flies = "rbxassetid://6445508213"

config.GlassShatter = "rbxassetid://2978605361"

config.Handgun32 = "rbxassetid://2752838113"
config.Handgun357 = "rbxassetid://2927757494"
config.Handgun380 = "rbxassetid://6730729816"
config.Handgun44 = "rbxassetid://3289442677"
config.Handgun45 = "rbxassetid://5108454724"
config.Handgun762 = "rbxassetid://9105246253"
config.Handgun762R = "rbxassetid://182342351"
config.Handgun9 = "rbxassetid://591033260"
config.Handgun9Makarov = "rbxassetid://4915487982"

config.HeavySlidingDoor = "rbxassetid://7509847163"

config.LiberatorLoad = "rbxassetid://17288307319"
config.LiberatorUnload = "rbxassetid://17288307582"

config.LMGBoxIn = "rbxassetid://198914776"
config.LMGBoxOut = "rbxassetid://198914822"

config.LoadBullet = "rbxassetid://5930878900"
config.LoadMortar = "rbxassetid://9116973855"

config.LockHandcuffs = "rbxassetid://9114764854"
config.UnlockHandcuffs = "rbxassetid://9114764731"

config.MainTheme = "rbxassetid://1832989888"

config.MetalDoorClose = "rbxassetid://3908308607"
config.MetalDoorOpen = "rbxassetid://9116871894"

config.MortarFire = "rbxassetid://346842816"
config.MortarIncoming = "rbxassetid://16037364835"

config.PistolChamber = "rbxassetid://17271274936"
config.PistolMagIn = "rbxassetid://1684280584"
config.PistolMagOut = "rbxassetid://1684280887"

config.PourSound = "rbxassetid://4527811806"

config.PowerWash = "rbxassetid://17872029328"

config.RadioOn = "rbxassetid://6667292786"
config.RadioOff = "rbxassetid://6667292683"

config.RecycleBottle = "rbxassetid://7431041001"

config.RevolverEmpty = "rbxassetid://2041035308"
config.RevolverHammer = "rbxassetid://160608684"
config.RevolverLoad = "rbxassetid://2211485081"

config.RifleChamber = "rbxassetid://936403709"
config.RifleClipIn = "rbxassetid://269079412"
config.RifleClipOut = "rbxassetid://268870109"

config.Rifle1075 = "rbxassetid://284938313"
config.Rifle127 = "rbxassetid://7369631961"
config.Rifle145 = "rbxassetid://2239383844"
config.Rifle545Soviet = "rbxassetid://802464084"
config.Rifle556NATO = "rbxassetid://5101189096"
config.Rifle762NATO = "rbxassetid://8060256373"
config.Rifle762Russian = "rbxassetid://6910514384"
config.Rifle762Soviet = "rbxassetid://5109593077"
config.RifleChargingHandle = "rbxassetid://198915379"

config.ShellEject = "rbxassetid://9113107265"

config.Shotgun12 = "rbxassetid://6770924452"
config.Shotgun20 = "rbxassetid://1543583455"
config.ShotgunLoad = "rbxassetid://254833667"
config.ShotgunPump = "rbxassetid://200289834"

config.SlotClick = "rbxassetid://7381723507"
config.SlotJackpot = "rbxassetid://1846251212"
config.SlotLose = "rbxassetid://1836245036"
config.SlotMultiplier = "rbxassetid://3416831713"
config.SlotSpin = "rbxassetid://9119220873"
config.SlotWin = "rbxassetid://8573765684"

config.ThunderClose = "rbxassetid://9126070144"
config.ThunderDistant = "rbxassetid://4961240438"

config.WeaponEmpty = "rbxassetid://132464034"

config.WindChimes = "rbxassetid://9120749869"

return config