--Contains all criminal charges
local config = {}

config.AntiPatriotic = {
    Name = "Anti-Patriotic Behavior";
    WithMod = "commit anti-patriotic behavior";
    Level = "Felony";
    Sentence = 18000;
}

config.ArmsTrafficking = {
    Name = "Firearms Trafficking";
    WithMod = "partake in firearms trafficking";
    Level = "Felony";
    Sentence = 18000;
}

config.Arson = {
    Name = "Arson";
    WithMod = "commit arson";
    Level = "Felony";
    Sentence = 7200;
}

config.Assault = {
    Name = "Assault";
    WithMod = "commit assault";
    Level = "Misdemeanor";
    Sentence = 1800;
}

config.Association = {
    Name = "Association with Known Dissidents";
    WithMod = "associate with known dissidents";
    Level = "Misdemeanor";
    Sentence = 1800;
}

config.Battery = {
    Name = "Battery";
    WithMod = "commit battery";
    Level = "Felony";
    Sentence = 18000;
}

config.Bribery = {
    Name = "Bribery";
    WithMod = "commit bribery";
    Level = "Felony";
    Sentence = 300;
}

config.Burglary = {
    Name = "Burglary";
    WithMod = "commit burglary";
    Level = "Felony";
    Sentence = 3600;
}

config.CorpseTampering = {
    Name = "Tampering with a Corpse";
    WithMod = "tamper with a corpse";
    Level = "Felony";
    Sentence = 14400;
}

config.Currency = {
    Name = "Currency Manipulation";
    WithMod = "manipulate currency";
    Level = "Felony";
    Sentence = 10800;
}

config.Defamation = {
    Name = "Defamation";
    WithMod = "commit defamation";
    Level = "Misdemeanor";
    Sentence = 3600;
}

config.DeliveryPrisoners = {
    Name = "Delivery of Articles to Prisoners";
    WithMod = "deliver articles to prisoners";
    Level = "Felony";
    Sentence = 18000;
}

config.Destruction = {
    Name = "Destruction of Property";
    WithMod = "destroy property";
    Level = "Felony";
    Sentence = 7200;
}

config.DiscloseSecret = {
    Name = "Disclosure of a State Secret";
    WithMod = "disclose a state secret";
    Level = "Felony";
    Sentence = 10800;
}

config.DisturbingPeace = {
    Name = "Disturbing the Peace";
    WithMod = "disturb the peace";
    Level = "Misdemeanor";
    Sentence = 600;
}

config.Escape = {
    Name = "Escaping from Custody";
    WithMod = "escape from custody";
    Level = "Felony";
    Sentence = 18000;
}

config.Evasion = {
    Name = "Evading Arrest";
    WithMod = "evade arrest";
    Level = "Misdemeanor";
    Sentence = 3600;
}

config.ExtremistCommunity = {
    Name = "Organizing an Extremist Community";
    WithMod = "organize an extremist community";
    Level = "Felony";
    Sentence = 14400;
}

config.FailComply = {
    Name = "Failure to Comply";
    WithMod = "fail to comply";
    Level = "Misdemeanor";
    Sentence = 600;
}

config.Fraud = {
    Name = "Fraud";
    WithMod = "commit fraud";
    Level = "Misdemeanor";
    Sentence = 7200;
}

config.Harassment = {
    Name = "Harassment";
    WithMod = "commit harassment";
    Level = "Misdemeanor";
    Sentence = 300;
}

config.HighTreason = {
    Name = "High Treason";
    WithMod = "commit high treason";
    Level = "Death";
    Sentence = 360000;
}

config.Kidnap = {
    Name = "Kidnapping";
    WithMod = "kidnap";
    Level = "Felony";
    Sentence = 72000;
}

config.Manslaughter = {
    Name = "Involuntary Manslaughter";
    WithMod = "commit involuntary manslaughter";
    Level = "Felony";
    Sentence = 28800;
}

config.Misinformation = {
    Name = "Spreading Misinformation";
    WithMod = "spread misinformation";
    Level = "Felony";
    Sentence = 7200;
}

config.Murder1 = {
    Name = "First Degree Murder";
    WithMod = "commit first degree murder";
    Level = "Felony";
    Sentence = 180000;
}

config.Murder2 = {
    Name = "Second Degree Murder";
    WithMod = "commit second degree murder";
    Level = "Felony";
    Sentence = 90000;
}

config.Obscenity = {
    Name = "Distribution of Obscene Material";
    WithMod = "distribute obscene material";
    Level = "Felony";
    Sentence = 18000;
}

config.Obstruction = {
    Name = "Obstruction of Justice";
    WithMod = "obstruct justice";
    Level = "Felony";
    Sentence = 18000;
}

config.PoliceImpersonation = {
    Name = "Impersonation of Law Enforcement";
    WithMod = "impersonate law enforcement";
    Level = "Misdemeanor";
    Sentence = 10800;
}

config.ProhibitedWeapon = {
    Name = "Possession of a Prohibited or Restricted Weapon";
    WithMod = "possess a prohibited or restricted weapon";
    Level = "Felony";
    Sentence = 36000;
}

config.PublicSpeaking = {
    Name = "Unauthorized Public Speaking";
    WithMod = "speak publicly without authorization";
    Level = "Misdemeanor";
    Sentence = 1800;
}

config.Riot = {
    Name = "Rioting";
    WithMod = "participate in a riot";
    Level = "Felony";
    Sentence = 7200;
}

config.Robbery = {
    Name = "Robbery";
    WithMod = "commit robbery";
    Level = "Felony";
    Sentence = 18000;
}

config.Sabotage = {
    Name = "Sabotage";
    WithMod = "commit sabotage";
    Level = "Felony";
    Sentence = 18000;
}

config.Subversion = {
    Name = "Subversion of Authority";
    WithMod = "subvert authority";
    Level = "Felony";
    Sentence = 10800;
}

config.Theft = {
    Name = "Theft";
    WithMod = "commit theft";
    Level = "Misdemeanor";
    Sentence = 900;
}

config.TheftState = {
    Name = "Theft of State Property";
    WithMod = "commit theft of state property";
    Level = "Felony";
    Sentence = 18000;
}

config.Treason = {
    Name = "Treason";
    WithMod = "commit treason";
    Level = "Felony";
    Sentence = 90000;
}

config.Trespassing = {
    Name = "Trespassing";
    WithMod = "trespass";
    Level = "Misdemeanor";
    Sentence = 1800;
}

config.TrespassingRestricted = {
    Name = "Trespassing on Restricted Property";
    WithMod = "trespass on restricted property";
    Level = "Misdemeanor";
    Sentence = 3600;
}

config.UnauthorizedAccess = {
    Name = "Unauthorized Access";
    WithMod = "gain unauthorized access";
    Level = "Felony";
    Sentence = 36000;
}

config.UnauthorizedRadio = {
    Name = "Unauthorized Radio Operation";
    WithMod = "operate a radio without authorization";
    Level = "Misdemeanor";
    Sentence = 3600;
}

config.UnlawfulAssembly = {
    Name = "Unlawful Assembly";
    WithMod = "participate in an unlawful assembly";
    Level = "Misdemeanor";
    Sentence = 1800;
}

config.UnlawfulCarry = {
    Name = "Unlawful Carrying of a Firearm";
    WithMod = "carry a firearm in an unlawful manner";
    Level = "Felony";
    Sentence = 18000;
}

config.UnlawfulDischarge = {
    Name = "Unlawful Discharge of a Firearm";
    WithMod = "discharge a firearm in an unlawful manner";
    Level = "Felony";
    Sentence = 5400;
}

config.UnlicensedGun = {
    Name = "Possession of an Unlicensed Firearm";
    WithMod = "possess an unlicensed firearm";
    Level = "Misdemeanor";
    Sentence = 18000;
}

config.Vandalism = {
    Name = "Vandalism";
    WithMod = "commit vandalism";
    Level = "Misdemeanor";
    Sentence = 600;
}

return config