--All articles of clothing removed from the game with the price to be refunded
local config = {}

--WENO STORE
config.BlackGoldSatinJacket = 7500
config.BlueSweatpants = 6500
config.BlueWenoSweatpants = 7500
config.BlueWenoTracksuit = 10000
config.CamoBDUJacket = 5000
config.CroppedBlueWindbreaker = 8000
config.FashionNovaBoxers = 650
config.FraudIncCrewneck = 8500
config.FrontEnemyTee = 1500
config.JellyPackHighWaisted = 5000
config.JellyPackSplitCrewneck = 9000
config.JellyPackSplitCroptop = 7000
config.JellyPackSweatpants = 5000
config.LoveBlack = 1500
config.PalaceKnitBlackWhite = 29000
config.PalaceKnitOrangeBlue = 29000
config.RedBlueNFSupreme = 190500
config.RollingStonesTee = 1500
config.Supreme8BallLeatherVarsity = 80500
config.SupremeBarbedMoto = 25000
config.SupremeDrillJersey = 7500
config.SupremeReflectiveCamo = 81150
config.SupremeSplitMustard = 20500
config.WenoRedVelvetSweatpants = 7500
config.WenoRedVelvetTracksuit = 10000
config.WhiteSupremeBoxers = 3000
config.YekimHoodie = 8500
config.YekimSweatpants = 7500
config.YellowYopstickCroptop = 6500
config.YopstickCrewneck = 8500
config.YopstickCroptop = 6500

return config