--This script contains a list of all webhooks
--For Discord webhooks, the "https://discord.com/api/webhooks/"
--at the beginning of the link should be omitted.
local config = {}

config.BankLog = {
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

config.BookingLog = {
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

config.DeathLog = {
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

config.EvidenceLog = {
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

config.GuidLog = {
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

config.ModLog = {
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

config.LicenseApp = {
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

config.NameRequests = {
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

config.PoliceLog ={
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

config.PropertyLog = {
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

config.WarrantLog = {
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

config.WeaponCheckout = {
    Link = "DISCORDWEBHOOK";
    Type = "Discord";
}

return config