--This script contains all animations
local config = {}

config.AKChamber = {
    Id = "rbxassetid://17272762780";
}

config.ARMagIn = {
    Id = "rbxassetid://16992919355";
}

config.ARMagOut = {
    Id = "rbxassetid://16992904465";
}

config.ArmsBack = {
    Id = "rbxassetid://18595668959";
}

config.Cuffed = {
    Id = "rbxassetid://3822797642";

    LockArms = true;
    PreventDraw = true;
}

config.Eat = {
    Id = "rbxassetid://4388912677";
}

config.DrawBack = {
    Id = "rbxassetid://17252629434";
}

config.DrawFront = {
    Id = "rbxassetid://17252516554";
}

config.DrawLeftHip = {
    Id = "rbxassetid://17252579111";
}

config.DrawLeftShoulder = {
    Id = "rbxassetid://17252590470";
}

config.DrawPocketBL = {
    Id = "rbxassetid://17252400472";
}

config.DrawPocketBR = {
    Id = "rbxassetid://17252379446";
}

config.DrawPocketFL = {
    Id = "rbxassetid://17252362058";
}

config.DrawPocketFR = {
    Id = "rbxassetid://17252286078";
}

config.DrawRightHip = {
    Id = "rbxassetid://17252558966";
}

config.DrawRightShoulder = {
    Id = "rbxassetid://17252545705";
}

config.Drink = {
    Id = "rbxassetid://4388937089";
}

config.FP45Load = {
    Id = "rbxassetid://17288342147";
}

config.FP45Unload = {
    Id = "rbxassetid://17288335957";
}

config.HandsUp = {
    Id = "rbxassetid://18425391327";

    CommandKeys = {
        "hands";
        "handsraised";
        "handsup";
        "reachsky";
        "reachforsky";
        "reachforthesky";
    };
    LockArms = true;
    OverrideLower = true;
    PreventDraw = true;
}

config.HoldSide = {
    Id = "rbxassetid://2668843468";
}

config.Kneel = {
    Id = "rbxassetid://2687733811";

    CanSprint = true;
    Crouch = true;
    Keybind = Enum.KeyCode.C;
    SpeedMod = 0;
}

config.Lie = {
    Id = "rbxassetid://5353813664";

    CommandKeys = {
        "lie";
        "lieback";
        "liedown";
    };
    LockArms = true;
    PreventDraw = true;
    SpeedMod = 0;
}

config.LMGBoxIn = {
    Id = "rbxssetid://17269674220";
}

config.LMGBoxOut = {
    Id = "rbxassetid://17269715362";
}

config.LMGBoxOut = {
    Id = "rbxssetid://17269674220";
}

config.OneHandSideHold = {
    Id = "rbxassetid://109214639253607"
}

config.PenguinDance = {
    Id = "rbxassetid://3145579476";

    CommandKeys = {
        "cpdance";
        "penguindance";
    };
    SpeedMod = 0;
}

config.PhoneCall = {
    Id = "rbxassetid://18425659164";

    CommandKeys = {
        "phonecall";
        "presshead";
    };
    LockArms = true;
    OverrideLower = true;
}

config.PistolAim = {
    Id = "rbxassetid://2668894750";
}

config.PistolChamber = {
    Id = "rbxassetid://17271230485";
}

config.PistolMagIn = {
    Id = "rbxassetid://16992983903";
}

config.PistolMagOut = {
    Id = "rbxassetid://16992973620";
}

config.Prone = {
    Id = "rbxassetid://18593965161";

    CommandKeys = {
        "bellylie";
        "getdown";
        "ground";
        "prone";
    };

    ContinueOnCuffed = true;
    Prone = true;
    SpeedMod = 0;
}

config.ProneHandgun = {
    Id = "rbxassetid://18595899122";

    SpeedMod = 0;
}

config.ProneRifle = {
    Id = "rbxassetid://18594102939";

    SpeedMod = 0;
}

config.RevolverLoad = {
    Id = "rbxassetid://17292848925";
}

config.RevolverUnload = {
    Id = "rbxassetid://17292691984";
}

config.RifleAim = {
    Id = "rbxassetid://2688302592";
}

config.RifleChargingHandle = {
    Id = "rbxassetid://17272682828";
}

config.RifleClipIn = {
    Id = "rbxassetid://17017525022";
}

config.RifleClipOut = {
    Id = "rbxassetid://17017525022";
}

config.RifleHold = {
    Id = "rbxassetid://2688305799";
}

config.ShotgunPump = {
    Id = "rbxassetid://17271707483";
}

config.ShotgunShellIn = {
    Id = "rbxassetid://17114681104";
}

config.Sleep = {
    Id = "rbxassetid://5353829453";

    CommandKeys = {
        "lieside";
        "rest";
        "sleep";
    };
    LockArms = true;
    PreventDraw = true;
    SpeedMod = 0;
}

config.SMGChamber = {
    Id = "rbxassetid://17271963700";
}

config.Sprint = {
    Id = "rbxassetid://4201753546";
}

config.Squat = {
    Id = "rbxassetid://2687807887";

    CommandKeys = {
        "squat";
        "slavsquat";
    };
    Crouch = true;
    SpeedMod = 0;
}

config.StenAim = {
    Id = "rbxassetid://3349100964";
}

config.StenMagIn = {
    Id = "rbxassetid://17144567848";
}

config.StenMagOut = {
    Id = "rbxassetid://17144542519";
}

config.Surrender = {
    Id = "rbxassetid://5311712943";

    CommandKeys = {
        "handshead";
        "handsonhead";
        "surrender";
    };
    LockArms = true;
    PreventDraw = true;
}

return config