--Contains configuration for all storage objects
local config = {}

config.StorageTypes = {
    DuplexStudio = {
        Capacity = 125;
        DisplayName = "Home Storage";
        Length = 2.75;
        Locked = true;
    };
    GaryHome = {
        Capacity = 100;
        DisplayName = "Home Storage";
        Length = 2.75;
        Locked = true;
    };
    KremenchukHome = {
        Capacity = 50;
        DisplayName = "Home Storage";
        Length = 2.75;
        Locked = true;
    };
    OneBedroom = {
        Capacity = 150;
        DisplayName = "Home Storage";
        Length = 2.75;
        Locked = true;
    };
    LuxuryHome = {
        Capacity = 250;
        DisplayName = "Home Storage";
        Length = 2.75;
        Locked = true;
    };
}

return config