local config = {}

config.EthnicDefaults = {
    Acehnese = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(135,103,90);
    };
    African = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(75,57,50);
    };
    ["Afro-Asian"] = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(75,57,50);
    };
    Ainu = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(210,161,140);
    };
    Akan = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    Albanian = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Aleut = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(120,92,80);
    };
    Altai = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    Amhara = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(75,57,50);
    };
    Andamanese = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(45,34,30);
    };
    Arab = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(165,126,110);
    };
    Armenian = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    Aromanian = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(225,172,150);
    };
    Asian = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(210,161,140);
    };
    Assyrian = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(165,126,110);
    };
    Austroasiatic = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(135,103,90);
    };
    Austronesian = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(135,103,90);
    };
    Avar = {
        Hair = Color3.fromRGB(83,61,50);
        Skin = Color3.fromRGB(180,138,120);
    };
    Azerbaijani = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(180,138,120);
    };
    Bai = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(225,172,150);
    };
    Balinese = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(150,114,100);
    };
    Baloch = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(120,92,80);
    };
    Banjar = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(90,69,60);
    };
    Bantenese = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(120,92,80);
    };
    Bashkir = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(135,103,90);
    };
    Basque = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(180,138,120);
    };
    Batak = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(120,92,80);
    };
    Belarusian = {
        Hair = Color3.fromRGB(83,61,50);
        Skin = Color3.fromRGB(225,172,150);
    };
    Berber = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(120,92,80);
    };
    Black = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    Bosniak = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(180,138,120);
    };
    Breton = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(225,172,150);
    };
    Buginese = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(90,69,60);
    };
    Bulgarian = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(180,138,120);
    };
    Buryat = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(120,92,80);
    };
    Catalan = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Cham = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(165,126,110);
    };
    Chechen = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(165,126,110);
    };
    Chewa = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    Chukchi = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(255,195,170);
    };
    ["Chukotko-Kamchatkan"] = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(165,126,110);
    };
    Chulym = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(210,161,140);
    };
    Chuvan = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(210,161,140);
    };
    Chuvash = {
        Hair = Color3.fromRGB(85,72,56);
        Skin = Color3.fromRGB(165,126,110);
    };
    Circassian = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(210,161,140);
    };
    Copt = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(165,126,110);
    };
    Cornish = {
        Hair = Color3.fromRGB(85,72,56);
        Skin = Color3.fromRGB(240,184,160);
    };
    Croat = {
        Hair = Color3.fromRGB(80,68,68);
        Skin = Color3.fromRGB(225,172,150);
    };
    Cypriot = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(180,138,120);
    };
    Czech = {
        Hair = Color3.fromRGB(184,151,120);
        Skin = Color3.fromRGB(240,184,160);
    };
    Dane = {
        Hair = Color3.fromRGB(222,188,153);
        Skin = Color3.fromRGB(225,172,150);
    };
    Dargin = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(195,149,130);
    };
    Dayak = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(150,114,100);
    };
    Dinka = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(45,34,30);
    };
    Dolgan = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    Dravidian = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(45,34,30);
    };
    Druze = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(165,126,110);
    };
    Dutch = {
        Hair = Color3.fromRGB(222,188,153);
        Skin = Color3.fromRGB(255,206,180);
    };
    Enets = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    English = {
        Hair = Color3.fromRGB(106,78,066);
        Skin = Color3.fromRGB(255,206,180);
    };
    Eskaleut = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(150,114,100);
    };
    Estonian = {
        Hair = Color3.fromRGB(229,200,168);
        Skin = Color3.fromRGB(210,161,140);
    };
    Eurasian = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(195,149,130);
    };
    European = {
        Hair = Color3.fromRGB(85,72,56);
        Skin = Color3.fromRGB(240,184,160);
    };
    Even = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(150,114,100);
    };
    Evenk = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(255,206,180);
    };
    Faroese = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(255,206,180);
    };
    Filipino = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(165,126,110);
    };
    Finn = {
        Hair = Color3.fromRGB(222,188,153);
        Skin = Color3.fromRGB(255,195,170);
    };
    French = {
        Hair = Color3.fromRGB(106,78,066);
        Skin = Color3.fromRGB(255,195,170);
    };
    Frisian = {
        Hair = Color3.fromRGB(151,121,097);
        Skin = Color3.fromRGB(255,195,170);
    };
    Fula = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(75,57,50);
    };
    Gagauz = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(195,149,130);
    };
    Georgian = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(195,149,130);
    };
    German = {
        Hair = Color3.fromRGB(230,206,168);
        Skin = Color3.fromRGB(240,184,160);
    };
    Greek = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(180,138,120);
    };
    Han = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(210,161,140);
    };
    Hausa = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    Hispanic = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Hui = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    Hungarian = {
        Hair = Color3.fromRGB(83,61,50);
        Skin = Color3.fromRGB(240,184,160);
    };
    Hutu = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(90,69,60);
    };
    Iban = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    Icelander = {
        Hair = Color3.fromRGB(230,206,168);
        Skin = Color3.fromRGB(255,206,180);
    };
    Igbo = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(75,57,50);
    };
    ["Indo-Aryan"] = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(165,126,110);
    };
    Iranic = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(165,126,110);
    };
    Irish = {
        Hair = Color3.fromRGB(145,85,61);
        Skin = Color3.fromRGB(255,206,180);
    };
    Italian = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(195,149,130);
    };
    Itelmen = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(150,114,100);
    };
    Izhorian = {
        Hair = Color3.fromRGB(184,151,120);
        Skin = Color3.fromRGB(255,195,170);
    };
    Jarai = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Javanese = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(150,114,100);
    };
    Jew = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    Kadazan = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Kalmyk = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(225,172,150);
    };
    Kamchadal = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(225,172,150);
    };
    Kanuri = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(90,69,60);
    };
    Karakalpak = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Karelian = {
        Hair = Color3.fromRGB(184,151,120);
        Skin = Color3.fromRGB(240,184,160);
    };
    Kashub = {
        Hair = Color3.fromRGB(222,188,153);
        Skin = Color3.fromRGB(240,184,160);
    };
    Kazakh = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Kerek = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    Khaka = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Khanty = {
        Hair = Color3.fromRGB(151,121,097);
        Skin = Color3.fromRGB(210,161,140);
    };
    Komi = {
        Hair = Color3.fromRGB(229,200,168);
        Skin = Color3.fromRGB(240,184,160);
    };
    Kongo = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    Korean = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(255,206,180);
    };
    Koryak = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(180,138,120);
    };
    Kumyk = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Kurd = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(150,114,100);
    };
    Kyrgyz = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    Latino = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Latvian = {
        Hair = Color3.fromRGB(184,151,120);
        Skin = Color3.fromRGB(255,206,180);
    };
    Lezgin = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(195,149,130);
    };
    Lithuanian = {
        Hair = Color3.fromRGB(230,206,168);
        Skin = Color3.fromRGB(255,195,170);
    };
    Livonian = {
        Hair = Color3.fromRGB(184,151,120);
        Skin = Color3.fromRGB(255,195,170);
    };
    Luba = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    Luo = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    ["Lun Bawang"] = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(150,114,100);
    };
    Luxembourger = {
        Hair = Color3.fromRGB(106,78,066);
        Skin = Color3.fromRGB(255,206,180);
    };
    Maasai = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    Macedonian = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(225,172,150);
    };
    Madurese = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(135,103,90);
    };
    Malay = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(135,103,90);
    };
    Maltese = {
        Hair = Color3.fromRGB(45,34,30);
        Skin = Color3.fromRGB(165,126,110);
    };
    Manchu = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    ["Mandé"] = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(75,57,50);
    };
    Mandarese = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(90,69,60);
    };
    Mansi = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(195,149,130);
    };
    Manx = {
        Hair = Color3.fromRGB(78,67,63);
        Skin = Color3.fromRGB(210,161,140);
    };
    Mari = {
        Hair = Color3.fromRGB(85,72,56);
        Skin = Color3.fromRGB(210,161,140);
    };
    Melanau = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(195,149,130);
    };
    Minahasan = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(135,103,90);
    };
    Minangkabau = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(150,114,100);
    };
    ["Mooré"] = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    Mongo = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(75,57,5);
    };
    Mongol = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(135,103,90);
    };
    Mongolic = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(135,103,90);
    };
    Montenegrin = {
        Hair = Color3.fromRGB(85,72,56);
        Skin = Color3.fromRGB(255,195,170);
    };
    Mordvin = {
        Hair = Color3.fromRGB(78,67,63);
        Skin = Color3.fromRGB(225,172,150);
    };
    Mossi = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    Murut = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(150,114,100);
    };
    Nanai = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Negidal = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(225,172,150);
    };
    Nenets = {
        Hair = Color3.fromRGB(80,68,68);
        Skin = Color3.fromRGB(255,206,180);
    };
    Nilotes = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(45,34,30);
    };
    Nivkh = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(135,103,90);
    };
    Nganasan = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Norwegian = {
        Hair = Color3.fromRGB(230,206,168);
        Skin = Color3.fromRGB(255,195,170);
    };
    Nuer = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    Nuristani = {
        Hair = Color3.fromRGB(80,68,68);
        Skin = Color3.fromRGB(180,138,120);
    };
    Occitan = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    Oroch = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(135,103,90);
    };
    Orok = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(240,184,160);
    };
    Oromo = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(75,57,50);
    };
    Ossetian = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(240,184,160);
    };
    Paleosiberian = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(135,103,90);
    };
    Persian = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    Pole = {
        Hair = Color3.fromRGB(85,72,56);
        Skin = Color3.fromRGB(255,206,180);
    };
    Polynesian = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(150,114,100);
    };
    Portuguese = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(180,138,120);
    };
    Romani = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(135,103,90);
    };
    Romanian = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(225,172,150);
    };
    Romansh = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(225,172,150);
    };
    Russian = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(210,161,140);
    };
    Ryukyuan = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(255,206,180);
    };
    Samaritan = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(165,126,110);
    };
    ["Sámi"] = {
        Hair = Color3.fromRGB(78,67,63);
        Skin = Color3.fromRGB(240,184,160);
    };
    Samoyedic = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Sasak = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(150,114,100);
    };
    Scottish = {
        Hair = Color3.fromRGB(181,82,57);
        Skin = Color3.fromRGB(255,206,180);
    };
    Selkup = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(195,149,130);
    };
    Semitic = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(165,126,110);
    };
    Serb = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(180,138,120);
    };
    Shor = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(195,149,130);
    };
    Shona = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(60,46,40);
    };
    ["Sino-Tibetan"] = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Slovak = {
        Hair = Color3.fromRGB(85,72,56);
        Skin = Color3.fromRGB(255,195,170);
    };
    Slovene = {
        Hair = Color3.fromRGB(151,121,097);
        Skin = Color3.fromRGB(240,184,160);
    };
    Somali = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(90,69,60);
    };
    Songhai = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(45,34,30);
    };
    Sorb = {
        Hair = Color3.fromRGB(184,151,120);
        Skin = Color3.fromRGB(255,195,170);
    };
    Soyot = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(195,149,130);
    };
    Spaniard = {
        Hair = Color3.fromRGB(106,78,066);
        Skin = Color3.fromRGB(210,161,140);
    };
    Sumbawa = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(135,103,90);
    };
    Sundanese = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Swede = {
        Hair = Color3.fromRGB(230,206,168);
        Skin = Color3.fromRGB(255,206,180);
    };
    Tai = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Tajik = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(255,206,180);
    };
    Tatar = {
        Hair = Color3.fromRGB(106,78,066);
        Skin = Color3.fromRGB(225,172,150);
    };
    Taz = {
        Hair = Color3.fromRGB(151,121,097);
        Skin = Color3.fromRGB(165,126,110);
    };
    Teleut = {
        Hair = Color3.fromRGB(83,61,50);
        Skin = Color3.fromRGB(150,114,100);
    };
    Tibetan = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    ["Tibeto-Burman"] = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Tigrayan = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(90,69,60);
    };
    Tofalar = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Tungusic = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(210,161,140);
    };
    Turk = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(165,126,110);
    };
    Turkic = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Turkmen = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Tuvan = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    Udege = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Udmurt = {
        Hair = Color3.fromRGB(145,85,61);
        Skin = Color3.fromRGB(240,184,160);
    };
    Ugric = {
        Hair = Color3.fromRGB(106,78,066);
        Skin = Color3.fromRGB(225,172,150);
    };
    Ukrainian = {
        Hair = Color3.fromRGB(222,188,153);
        Skin = Color3.fromRGB(210,161,140);
    };
    Ulch = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(210,161,140);
    };
    Uralic = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(210,161,140);
    };
    Uyghur = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Uzbek = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(180,138,120);
    };
    Valakese = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(135,103,90);
    };
    Vepsian = {
        Hair = Color3.fromRGB(184,151,120);
        Skin = Color3.fromRGB(210,161,140);
    };
    Welsh = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(195,149,130);
    };
    White = {
        Hair = Color3.fromRGB(106,78,066);
        Skin = Color3.fromRGB(225,172,150);
    };
    Yamato = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(210,161,140);
    };
    Yakut = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(210,161,140);
    };
    Yeniseian = {
        Hair = Color3.fromRGB(44,34,43);
        Skin = Color3.fromRGB(165,126,110);
    };
    Yoruba = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(105,80,70);
    };
    Yukaghir = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(180,138,120);
    };
    Yupik = {
        Hair = Color3.fromRGB(59,48,36);
        Skin = Color3.fromRGB(195,149,130);
    };
    Zhuang = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(255,206,180);
    };
    Zulu = {
        Hair = Color3.fromRGB(9,8,6);
        Skin = Color3.fromRGB(90,69,60);
    };
}

--Source: https://www.collectedwebs.com/art/colors/hair/
config.Hair = {
    Color3.fromRGB(151,121,097); --Ash Brown
    Color3.fromRGB(167,133,106); --Light Brown
    Color3.fromRGB(106,78,066); --Brown
    Color3.fromRGB(80,68,68); --Chestnut Brown
    Color3.fromRGB(78,67,63); --Medium Brown
    Color3.fromRGB(85,72,56); --Golden Brown
    Color3.fromRGB(59,48,36); --Dark Brown
    Color3.fromRGB(83,61,50); --Dark Auburn
    Color3.fromRGB(145,85,61); --Light Auburn
    Color3.fromRGB(141,74,67); --Dark Red
    Color3.fromRGB(181,82,57); --Light Red
    Color3.fromRGB(165,107,70); --Strawberry Blonde
    Color3.fromRGB(184,151,120); --Honey Blonde
    Color3.fromRGB(222,188,153); --Ash Blonde
    Color3.fromRGB(229,200,168); --Golden Blonde
    Color3.fromRGB(230,206,168); --Light Blonde
    Color3.fromRGB(255,245,225); --White Blonde
    Color3.fromRGB(220,208,186); --Bleached Blonde
    Color3.fromRGB(202,191,177); --Platinum Blonde
    Color3.fromRGB(214,196,194); --Light Gray
    Color3.fromRGB(183,166,158); --Medium Gray
    Color3.fromRGB(113,99,90); --Dark Gray
    Color3.fromRGB(44,34,43); --Off Black
    Color3.fromRGB(9,8,6); --Black
}

--Source: https://www.researchgate.net/figure/RGB-values-for-different-human-skin-color-tones_fig3_310443424
config.Skin = {
    Color3.fromRGB(255,206,180);
    Color3.fromRGB(255,195,170);
    Color3.fromRGB(240,184,160);
    Color3.fromRGB(225,172,150);
    Color3.fromRGB(210,161,140);
    Color3.fromRGB(195,149,130);
    Color3.fromRGB(180,138,120);
    Color3.fromRGB(165,126,110);
    Color3.fromRGB(150,114,100);
    Color3.fromRGB(135,103,90);
    Color3.fromRGB(120,92,80);
    Color3.fromRGB(105,80,70);
    Color3.fromRGB(90,69,60);
    Color3.fromRGB(75,57,50);
    Color3.fromRGB(60,46,40);
    Color3.fromRGB(45,34,30);
}

local colorTypes = {"Hair", "Skin"}
for ethnicity, defaults in pairs(config.EthnicDefaults) do
    for i, colorType in ipairs(colorTypes) do
        for j, color in ipairs(config[colorType]) do
            if color == defaults[colorType] then
                config.EthnicDefaults[ethnicity][colorType] = j
                break
            end
        end
    end
end

return config