---All tips which appear on the main menu
local config = {}

config.Cyclical = {
    "When you die, all the items in your inventory will be dropped, including \z
    all the cash in your wallet. Be sure to deposit what you're not using!";

    "The day-night cycle in game is 24 real-world hours! The game clock is \z
    synced with Alaskan Standard Time (GMT-9).";

    "The Valak people are the indigenous people of the island of Bloxell. \z
    They have a unique Polynesian language, written in the Cyrillic script.";

    "Be careful with ATMs. A thief could swipe your money as it is being \z
    dispensed!";

    "Bloxell was a colony of the Russian Empire until 1917. A large Slavic \z
    population still exists on the island due to settlers.";

    "A brutal civil war was fought across Bloxell from 2019 - 2021. The peace \z
    treaty signed split Bloxell in two, with the Republic of Bloxell in the \z
    south, and the State of North Bloxell in the north.";

    "The city of Bloxford, where this game takes place, was split in two \z
    along the Carver River by the Detroit Accords, which ended the Bloxell \z
    Civil War.";

    "Bloxell is a small island in the Pacific, located south of Alaska.";

    "After the war, many criminal gangs seized power during the power vaccuum \z
    that followed. They are engaged primarily in smuggling and the sale of \z
    illegal goods across the city.";

    "Much of the city was rebuilt following the intense fighting during the \z
    Battle of Bloxford of the Bloxell Civil War. Some reminders of the \z
    war still litter the city to this day.";

    "The church bell rings every hour, on the hour. The number of rings \z
    will let you know what time it is.";

    "You can drop an item on the ground with /drop, or set it wherever you're \z
    currently holding it with /set!";

    "Downtown Chronicles 2 is actually the seventh game in the Bloxell \z
    series. The first game was Detroit High School (later renamed to Bloxell \z
    Roleplay), released in October 2016, and the most popular was Downtown \z
    Chronicles, released in April 2018, the game this game is based on!";

    "Bloxell: Whitelisted Roleplay (Bloxell 4.0) was a groundbreaking game \z
    in the genre. It was the first game of its type on Roblox to have a fully \z
    in-game character customization system, developed in August 2017!";

    "The map for Downtown Chronicles 2 was entirely built anew by \z
    theRealDogGodz and SashaBachvarov, but was based on the map for the \z
    original Downtown Chronicles made by Submersibles!";

    "Many buildings from the original Downtown Chronicles have been \z
    reimagined for Downtown Chronicles 2. Even if you're familiar with the \z
    original map, it's worth exploring anew!";

    "There are many commands used in roleplay in this game. Other than /me, \z
    you have /do, /my, /ame, /melow, /dolow, /b, /ooc, /s, /shout, and /low!";

    "This is a roleplay game, in which you're using a character. All \z
    interactions and messages should be from the perspective of your \z
    character (or IC, In Character), unless you're using the /b or /ooc \z
    commands for out of character (OOC) messages.";

    "When it's storming, lightning can strike without warning! It's best to \z
    avoid open or elevated spaces!";

    "99% of gamblers quit right before they win it big! Head over to the Laki \z
    Club today to try your luck!";

    "The ATM is not a \"free money machine\". Once you run out of money in \z
    your bank account, you will no longer be able to withdraw from it.";

    "\"Мама ле Валаке\", or \"Mama le Valake\" in the Latin script, is a \z
    common Valakese (indigenous Bloxellian) rallying cry. It translates to \z
    \"glory to Bloxell!\"";

    "Valakese, also called Valak, is a con-lang developed for the Bloxell \z
    games, out of Gitrog's passion for linguistics. It is present throughout \z
    the game, intended to be used by the indigenous population of Bloxell.";

    "You can apply for citizenship, firearms licenses, and other documents \z
    at your local police station.";

    "The Red Stag is always hiring bartenders, it's one of the most popular \z
    jobs for immigrants in North Bloxford.";

    "The Laki Club is a great way to spend your time, and possibly win some \z
    money. The machines there even offer free drinks sometimes!";

    "If you want to fit in more with other players, you should get out of \z
    the arrivals jumpsuit and get yourself some clothing at OOrkan Clothing. \z
    Other players are more receptive to those not dressed like new players!";

    "Bloxell is not America, but its own independent nation. Trying to bring \z
    up the Constitution and the rights you have under it will get you laughed \z
    at.";

    "Following the Bloxell Civil War, Bloxell drastically reduced immigration \z
    requirements, hoping to bring in more residents to their cities to \z
    replace those fallen in war.";

    "When you hear gunfire, don't run towards it to see what's going on, run \z
    away! It's hard to predict where a bullet will end up, but being far away \z
    prevents you from losing your items and money due to a stray bullet.";

    "You can rent an apartment at the bank, which will become a spawn point \z
    for you, and you'll be able to store items there securely! Just make sure \z
    to pay your rent every month!";

    "At the locksmith, you can clone the keys to your apartment or storage \z
    for a friend. Just make sure to give them to people you trust, because \z
    replacing the lock is expensive!";

    "The Kremenchutskyy Projects, located just south of the Memorial Park, \z
    are Bloxford's most affordable housing unit. They were funded by Mykhailo \z
    Kremenchuk, Bloxford's first jackpot winner.";

    "Citizens looking to fulfill their patriotic duty to protect their country \z
    can join the National Guard, who are called up to serve when states of \z
    emergency are declared.";

    "The National Guard and police keep detailed records on who checks out \z
    which weapons, and if they are not returned, they will search for it \z
    until its found. Think twice before taking a service weapon.";

    "Blood splatters. If you're shot, or you're near someone when they get \z
    shot, you might want to get a change of clothes. Being covered in blood \z
    can attract unwanted attention, and flies, if you leave it too long.";

    "The Laki Club is offering citizens of North Bloxell a welcome bonus! \z
    Upon spending their first ₲2,000, players will be awarded 50 free spins!";

    "The currency of Bloxell is the Bloxellian GCH, often referred to as\z
    \"Garies\", and was established as a trans-Bloxellian currency by the \z
    Detroit Accords. The exchange rate is fixed to the dollar, at ₲127 to $1.";

    "Most guns must be chambered manually after being loaded. You can do this \z
    by pressing the F key.";

    "NPC talking too slow? Press Return to skip their dialogue! It even works \z
    on this text, try it out!";

    "Any kind of automatic weapon is generally considered as illegal. But, \z
    if you have a Machine Gun Permit, you can legally possess these. They \z
    require written permission from the president in order to get, or a TIB \z
    score of 100!";

    "Any equipment belonging to the government, such as police or military \z
    issue weapons, or even something like a power washer, is state property. \z
    Getting caught with something like that, or keeping it off duty, could \z
    land you a felony.";

    "Be careful about when and where you commit crimes. You never know who's \z
    watching, recording, or even an undercover cop. You don't want to get a \z
    felony conviction.";

    "The Pilkington family runs the oldest clothing store in Bloxell, which \z
    can be found on Božidar Nikolić Street in North Bloxford. You can find \z
    all types of formal attire there.";

    "The North Bloxford Correctional Facility was opened in 2024, one of \z
    the State of North Bloxell's most ambitious projects. This towering \z
    skyscraper was built following the war, as part of President Nikolić's \z
    \"Plan for Order.\"";

    "The Ministry of Internal Affairs is the primary law enforcment agency \z
    in the State of North Bloxell. They are broken up into three divisions: \z
    the patrol division, the investigative division, and the tax division.";

    "When stopped by police, it's best to comply. They have the power to put \z
    you away for a long time, or even to kill your character for good.";
}

config.Scroll = "You can use the scroll wheel to switch between character cards"

return config