---The configuration for buying guns at the gun store
local config = {}

config.Name = "North Bloxford Guns and Ammo"

config.TakesCard = true
config.TakesCash = true

config.Items = {
    {
        Name = "AB10";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 68600;
    };
    {
        Name = "AK74Mag30";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 2000;
    };
    {
        Name = "AKS74U";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 76200;
    };
    {
        Name = "AlaskanRedhawk";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 190500;
    };
    {
        Name = "ASH781";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 92700;
    };
    {
        Name = "Berdan";
        Type = "Item";
        SellIf = "NorthHDP";
        Price = 125000;
    };
    {
        Name = "CZ99";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 115000;
    };
    {
        Name = "CZ99Mag15";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 4200;
    };
    {
        Name = "F2000";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 380000;
    };
    {
        Name = "FP45";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 4700;
    };
    {
        Name = "FS2000";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 285750;
    };
    {
        Name = "G3";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 552000;
    };
    {
        Name = "G3Mag20";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 2500;
    };
    {
        Name = "Glock19";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 63500;
    };
    {
        Name = "Glock19Mag15";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 2800;
    };
    {
        Name = "HiPointC9";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 25000;
    };
    {
        Name = "C9Mag8";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 1500;
    };
    {
        Name = "HK417Mag20";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 8900;
    };
    {
        Name = "LCP";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 43000;
    };
    {
        Name = "LCPMag6";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 4300;
    };
    {
        Name = "Luger";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 97000;
    };
    {
        Name = "LugerMag8";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 5500;
    };
    {
        Name = "M15";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 73500;
    };
    {
        Name = "M16";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 88900;
    };
    {
        Name = "M1911";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 72500;
    };
    {
        Name = "M1911Mag7";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 3000;
    };
    {
        Name = "M16Mag20";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 1750;
    };
    {
        Name = "M3";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 34000;
    };
    {
        Name = "M3Mag32";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 4500;
    };
    {
        Name = "M57";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 50000;
    };
    {
        Name = "M57Mag9";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 6000;
    };
    {
        Name = "M70B3";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 145000;
    };
    {
        Name = "M70Mag30";
        Type = "Item";
        SellIf = "NorthGunBuyer";
        Price = 3200;
    };
    {
        Name = "M72B1";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 150000;
    };
    {
        Name = "M77";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 174000;
    };
    {
        Name = "M77Mag20";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 6200;
    };
    {
        Name = "M84";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 616500;
    };
    {
        Name = "M85Mag30";
        Type = "Item";
        SellIf = "NorthGunBuyer";
        Price = 5000;
    };
    {
        Name = "M9";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 60000;
    };
    {
        Name = "M92";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 142000;
    };
    {
        Name = "M93";
        Type = "Item";
        SellIf = "NorthHDP";
        Price = 698500;
    };
    {
        Name = "M93Mag5";
        Type = "Item";
        SellIf = "NorthHDP";
        Price = 19000;
    };
    {
        Name = "M9Mag15";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 3000;
    };
    {
        Name = "MAC10";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 154000;
    };
    {
        Name = "MAC1045Mag32";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 5700;
    };
    {
        Name = "MakarovMag8";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 3000;
    };
    {
        Name = "Mosin";
        Type = "Item";
        SellIf = "NorthHDP";
        Price = 57000;
    };
    {
        Name = "MosinClip5";
        Type = "Item";
        SellIf = "NorthHDP";
        Price = 90;
    };
    {
        Name = "Mossberg50012";
        Type = "Item";
        SellIf = "NorthHDP";
        Price = 85000;
    };
    {
        Name = "Mossberg50020";
        Type = "Item";
        SellIf = "NorthHDP";
        Price = 76200;
    };
    {
        Name = "MR308";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 932000;
    };
    {
        Name = "Nagant1895";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 114000;
    };
    {
        Name = "PKMBox100";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 5100;
    };
    {
        Name = "PPSh";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 52300;
    };
    {
        Name = "PPShDrum71";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 11300;
    };
    {
        Name = "PTR91";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 151000;
    };
    {
        Name = "Skorpion61";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 115000;
    };
    {
        Name = "SCAR16S";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 487550;
    };
    {
        Name = "SCARLMag20";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 4500;
    };
    {
        Name = "Skorpion32Mag20";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 3800;
    };
    {
        Name = "SKS";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 66150;
    };
    {
        Name = "SKSClip10";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 150;
    };
    {
        Name = "STANAG30";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 2000;
    };
    {
        Name = "Sten";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 19850;
    };
    {
        Name = "StenMag32";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 7200;
    };
    {
        Name = "SuperRedhawk";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 190500;
    };
    {
        Name = "SuperShorty";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 133350;
    };
    {
        Name = "Taurus605";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 47000;
    };
    {
        Name = "TEC9";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 114300;
    };
    {
        Name = "TEC9Mag32";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 5200;
    };
    {
        Name = "Thompson";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 431800;
    };
    {
        Name = "ThompsonMag30";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 4000;
    };
    {
        Name = "TT33";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 54000;
    };
    {
        Name = "TTMag8";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 3200;
    };
    {
        Name = "UZI";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 165000;
    };
    {
        Name = "UZIMag32";
        Type = "Item";
        SellIf = "NorthMGP";
        Price = 2500;
    };
    {
        Name = "ZPAPM70";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 135000;
    };
    {
        Name = "ZPAPM70UF";
        Type = "Item";
        SellIf = "NorthHDPMGP";
        Price = 140000;
    };
    {
        Name = "ZPAPM85";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 152000;
    };
    {
        Name = "ZPAPM92";
        Type = "Item";
        SellIf = "NorthLTC";
        Price = 138000;
    };
}

return config