---The configuration for a test shop for studio use
local config = {}

config.Name = "OOrkan Apparel"

config.TakesCard = true
config.TakesCash = true

config.Items = {
    --Shirts
    {
        Name = "AshBalmainTee";
        Type = "Clothing";
        Price = 55880;
    };
    {
        Name = "BeigeSweater";
        Type = "Clothing";
        Price = 7000;
    };
    {
        Name = "Black6Tracksuit";
        Type = "Clothing";
        Price = 10000;
    };
    {
        Name = "BlackPuffer";
        Type = "Clothing";
        Price = 11000;
    };
    {
        Name = "BlackNorthFacePufferXGrayHoodie";
        Type = "Clothing";
        Price = 41910;
    };
    {
        Name = "BlackSupremeXChampion";
        Type = "Clothing";
        Price = 38100;
    };
    {
        Name = "BlackTee";
        Type = "Clothing";
        Price = 1500;
    };
    {
        Name = "BLoxTee";
        Type = "Clothing";
        Price = 9500;
    };
    {
        Name = "BlueBlackMotorcycle";
        Type = "Clothing";
        Price = 5500;
    };
    {
        Name = "BusyGaming";
        Type = "Clothing";
        Price = 1500;
    };
    {
        Name = "ColdestTee";
        Type = "Clothing";
        Price = 1500;
    };
    {
        Name = "DDRTracksuitTop";
        Type = "Clothing";
        Price = 6350;
    };
    {
        Name = "DenimJacketWhiteHoodie";
        Type = "Clothing";
        Price = 8500;
    };
    {
        Name = "DragonButtonDown";
        Type = "Clothing";
        Price = 10000;
    };
    {
        Name = "GrayShirtDenimJacket";
        Type = "Clothing";
        Price = 6500;
    };
    {
        Name = "GreenFlannel";
        Type = "Clothing";
        Price = 6500;
    };
    {
        Name = "GreenJersey";
        Type = "Clothing";
        Price = 3500;
    };
    {
        Name = "GreenPatagoniaCrewneck";
        Type = "Clothing";
        Price = 3810;
    };
    {
        Name = "GreenPlaidShirt";
        Type = "Clothing";
        Price = 6500;
    };
    {
        Name = "GrimyWhiteTanktop";
        Type = "Clothing";
        Price = 500;
    };
    {
        Name = "GuitarTeeBlackJacket";
        Type = "Clothing";
        Price = 5500;
    };
    {
        Name = "WatchedBIOTee";
        Type = "Clothing";
        Price = 1500;
    };
    {
        Name = "LibertyDeathTee";
        Type = "Clothing";
        Price = 1500;
    };
    {
        Name = "LovePizza";
        Type = "Clothing";
        Price = 1500;
    };
    {
        Name = "LovePurchase";
        Type = "Clothing";
        Price = 1500;
    };
    {
        Name = "NukingLegal";
        Type = "Clothing";
        Price = 1500;
    };
    {
        Name = "OffWhiteVloneBlackTee";
        Type = "Clothing";
        Price = 31750;
    };
    {
        Name = "OffWhiteVloneWhiteTee";
        Type = "Clothing";
        Price = 31750;
    };
    {
        Name = "PastelTopGrayJacket";
        Type = "Clothing";
        Price = 5500;
    };
    {
        Name = "PaycheckBlackHoodie";
        Type = "Clothing";
        Price = 8500;
    };
    {
        Name = "PaycheckBlackHoodiePurple";
        Type = "Clothing";
        Price = 8500;
    };
    {
        Name = "PaycheckWhiteHoodie";
        Type = "Clothing";
        Price = 8500;
    };
    {
        Name = "PaycheckWhiteHoodiePurple";
        Type = "Clothing";
        Price = 8500;
    };
    {
        Name = "PinkFlamingoButtonUp";
        Type = "Clothing";
        Price = 6000;
    };
    {
        Name = "PumpIt";
        Type = "Clothing";
        Price = 1500;
    };
    {
        Name = "PurplePuffer";
        Type = "Clothing";
        Price = 16150;
    };
    {
        Name = "PurpleTealTop";
        Type = "Clothing";
        Price = 1750;
    };
    {
        Name = "TannedLeatherJacket";
        Type = "Clothing";
        Price = 24000;
    };
    {
        Name = "TrueHero";
        Type = "Clothing";
        Price = 1500;
    };
    {
        Name = "WhiteBalenciagaTee";
        Type = "Clothing";
        Price = 88900;
    };
    {
        Name = "WhiteOffShoulderTop";
        Type = "Clothing";
        Price = 6350;
    };
    {
        Name = "WhiteRomaniaTee";
        Type = "Clothing";
        Price = 2540;
    };
    {
        Name = "WhiteTanktop";
        Type = "Clothing";
        Price = 1000;
    };
    {
        Name = "WhiteTee";
        Type = "Clothing";
        Price = 1000;
    };
    {
        Name = "WhiteUnderArmorTee";
        Type = "Clothing";
        Price = 2540;
    };

    --Pants
    {
        Name = "AmiriJeansLouboutins";
        Type = "Clothing";
        Price = 152400;
    };
    {
        Name = "BeautifulYou";
        Type = "Clothing";
        Price = 6000;
    };
    {
        Name = "BikerJeansBlackYeezys";
        Type = "Clothing";
        Price = 25400;
    };
    {
        Name = "BikerJeansJordan11s";
        Type = "Clothing";
        Price = 44150;
    };
    {
        Name = "Black6Sweatpants";
        Type = "Clothing";
        Price = 6500;
    };
    {
        Name = "BlackLeggingsWhiteSneakers";
        Type = "Clothing";
        Price = 6200;
    };
    {
        Name = "BlackJeans";
        Type = "Clothing";
        Price = 3500;
    };
    {
        Name = "BlackJeansSneakers";
        Type = "Clothing";
        Price = 3500;
    };
    {
        Name = "BlackJeansWhiteShoes";
        Type = "Clothing";
        Price = 3500;
    };
    {
        Name = "BlackLevisJordan4s";
        Type = "Clothing";
        Price = 38100;
    };
    {
        Name = "BlackSamuraiPants";
        Type = "Clothing";
        Price = 4500;
    };
    {
        Name = "BlueBikerJeansJordan4s";
        Type = "Clothing";
        Price = 38100;
    };
    {
        Name = "BlueStonewashJeans";
        Type = "Clothing";
        Price = 6350;
    };
    {
        Name = "BlueTopShortShorts";
        Type = "Clothing";
        Price = 16000;
    };
    {
        Name = "CasualBlackJeans";
        Type = "Clothing";
        Price = 3500;
    };
    {
        Name = "DarkGreenJeans";
        Type = "Clothing";
        Price = 3500;
    };
    {
        Name = "DDRTracksuitBottom";
        Type = "Clothing";
        Price = 6350;
    };
    {
        Name = "GrayStonewashJeans";
        Type = "Clothing";
        Price = 6350;
    };
    {
        Name = "JeanShorts";
        Type = "Clothing";
        Price = 2500;
    };
    {
        Name = "JeanShortsWhiteShoes";
        Type = "Clothing";
        Price = 3000;
    };
    {
        Name = "KhakiChinoBlueConverse";
        Type = "Clothing";
        Price = 15000;
    };
    {
        Name = "KhakiPants";
        Type = "Clothing";
        Price = 4500;
    };
    {
        Name = "KhakiPantsBlackSneakers";
        Type = "Clothing";
        Price = 15000;
    };
    {
        Name = "KhakiPantsConverse";
        Type = "Clothing";
        Price = 15000;
    };
    {
        Name = "PinkJeans";
        Type = "Clothing";
        Price = 3500;
    };
    {
        Name = "RippedJeansWhiteVans";
        Type = "Clothing";
        Price = 12700;
    };
    {
        Name = "TrueJeansJordan11s";
        Type = "Clothing";
        Price = 116205;
    };
}

return config