---The configuration for a test shop for studio use
local config = {}

config.Name = "Pilkington's Apparel"

config.TakesCard = true
config.TakesCash = true

config.Items = {
    --Suits
    {
        Name = "Beige 3 Piece Suit";
        Pants = "Beige3PieceBottom";
        Shirt = "Beige3PieceTop";
        Type = "Suit";
        Price = 40000;
    };
    {
        Name = "Black 2 Buttoned Suit";
        Pants = "Black2ButtonBottom";
        Shirt = "Black2ButtonTop";
        Type = "Suit";
        Price = 25000;
    };
    {
        Name = "Black Classic Business Suit";
        Pants = "BlackClassicBusinessBottom";
        Shirt = "BlackClassicBusinessTop";
        Type = "Suit";
        Price = 38000;
    };
    {
        Name = "Black Classic Fitted Suit";
        Pants = "BlackClassicFitBottom";
        Shirt = "BlackClassicFitTop";
        Type = "Suit";
        Price = 70000;
    };
    {
        Name = "Black Fur Trench Coat";
        Pants = "BlackFurTrenchBottom";
        Shirt = "BlackFurTrenchTop";
        Type = "Suit";
        Price = 50000;
    };
    {
        Name = "Black & Gold Suit";
        Pants = "BlackGoldSuitBottom";
        Shirt = "BlackGoldSuitTop";
        Type = "Suit";
        Price = 95000;
    };
    {
        Name = "Black Label 3 Piece Suit";
        Pants = "BlackLabel3PieceBottom";
        Shirt = "BlackLabel3PieceTop";
        Type = "Suit";
        Price = 100000;
    };
    {
        Name = "Black Label Blazer";
        Pants = "BlackLabelBlazerBottom";
        Shirt = "BlackLabelBlazerTop";
        Type = "Suit";
        Price = 36000;
    };
    {
        Name = "Black Label Open Suit";
        Pants = "BlackLabelBottom";
        Shirt = "BlackLabelTop";
        Type = "Suit";
        Price = 87500;
    };
    {
        Name = "Black Label Peacoat";
        Pants = "BlackLabelPeacoatBottom";
        Shirt = "BlackLabelPeacoatTop";
        Type = "Suit";
        Price = 110000;
    };
    {
        Name = "Black Label Suit with Bowtie";
        Pants = "BlackLabelBowtieBottom";
        Shirt = "BlackLabelBowtieTop";
        Type = "Suit";
        Price = 65000;
    };
    {
        Name = "Black Label Suit with Vest";
        Pants = "BlackLabelVestBottom";
        Shirt = "BlackLabelVestTop";
        Type = "Suit";
        Price = 100000;
    };
    {
        Name = "Black Label Trench Coat";
        Pants = "BlackLabelTrenchBottom";
        Shirt = "BlackLabelTrenchTop";
        Type = "Suit";
        Price = 50000;
    };
    {
        Name = "Black Label Tuxedo";
        Pants = "BlackLabelTuxBottom";
        Shirt = "BlackLabelTuxTop";
        Type = "Suit";
        Price = 65000;
    };
    {
        Name = "Black Leisure Suit";
        Pants = "BlackLeisureBottom";
        Shirt = "BlackLeisureTop";
        Type = "Suit";
        Price = 25000;
    };
    {
        Name = "Brown 2 Buttoned Suit";
        Pants = "Brown2ButtonBottom";
        Shirt = "Brown2ButtonTop";
        Type = "Suit";
        Price = 25000;
    };
    {
        Name = "Dragon Patterned 3 Piece Suit";
        Pants = "Dragon3PieceBottom";
        Shirt = "Dragon3PieceTop";
        Type = "Suit";
        Price = 60000;
    };
    {
        Name = "Herringbone 3 Piece Suit";
        Pants = "Herringbone3PieceBottom";
        Shirt = "Herringbone3PieceTop";
        Type = "Suit";
        Price = 40000;
    };
    {
        Name = "Gray 2 Buttoned Suit";
        Pants = "Gray2ButtonBottom";
        Shirt = "Gray2ButtonTop";
        Type = "Suit";
        Price = 25000;
    };
    {
        Name = "Gray Blazer with Turtleneck";
        Pants = "GrayBlazerTurtleneckBottom";
        Shirt = "GrayBlazerTurtleneckTop";
        Type = "Suit";
        Price = 40000;
    };
    {
        Name = "Navy 2 Buttoned Suit";
        Pants = "Navy2ButtonBottom";
        Shirt = "Navy2ButtonTop";
        Type = "Suit";
        Price = 25000;
    };
    {
        Name = "Tan 3 Piece Suit";
        Pants = "Tan3PieceBottom";
        Shirt = "Tan3PieceTop";
        Type = "Suit";
        Price = 40000;
    };
    {
        Name = "White and Gold Suit with Purple Vest";
        Pants = "WhiteGoldSuitBottom";
        Shirt = "WhiteGoldSuitTop";
        Type = "Suit";
        Price = 190000;
    };

    --Shirts
    {
        Name = "BlackDressShirt";
        Type = "Clothing";
        Price = 8400;
    };
    {
        Name = "LacedTopCuffs";
        Type = "Clothing";
        Price = 17000;
    };
    {
        Name = "PinkArgyle";
        Type = "Clothing";
        Price = 19000;
    };
    {
        Name = "PinkFormalShirt";
        Type = "Clothing";
        Price = 6500;
    };
    {
        Name = "PinkShirtNavyVest";
        Type = "Clothing";
        Price = 17500;
    };
    {
        Name = "WhiteDressBlueVest";
        Type = "Clothing";
        Price = 16000;
    };
    {
        Name = "WhiteDressHarness";
        Type = "Clothing";
        Price = 17150;
    };

    --Pants
    {
        Name = "BeigeDressPants";
        Type = "Clothing";
        Price = 15000;
    };
    {
        Name = "BlackDressPants";
        Type = "Clothing";
        Price = 15000;
    };
    {
        Name = "BlackDressTrousers";
        Type = "Clothing";
        Price = 15000;
    };
    {
        Name = "BlackPants";
        Type = "Clothing";
        Price = 5700;
    };
    {
        Name = "BlackWhiteFloralDress";
        Type = "Clothing";
        Price = 12000;
    };
    {
        Name = "BrownCasualPants";
        Type = "Clothing";
        Price = 12500;
    };
    {
        Name = "GrayDressPants";
        Type = "Clothing";
        Price = 15000;
    };
    {
        Name = "GrayPlaidSkirt";
        Type = "Clothing";
        Price = 3800;
    };
    {
        Name = "GreenFestiveGown";
        Type = "Clothing";
        Price = 35000;
    };
    {
        Name = "GreenPants";
        Type = "Clothing";
        Price = 4500;
    };
    {
        Name = "PinkSparkleGown";
        Type = "Clothing";
        Price = 12500;
    };
    {
        Name = "RedSparkleDress";
        Type = "Clothing";
        Price = 12500;
    };
}

return config