local config = {}

config["Bloxell Intelligence Organization"] = {
    TeamColor = BrickColor.new("Mulberry");
}

config["Bloxford Police Department"] = {
    TeamColor = BrickColor.new("Storm blue");
}

config.Incarcerated = {
    TeamColor = BrickColor.new("Neon orange");
}

config["National Guard"] = {
    TeamColor = BrickColor.new("Earth green");
}

config["Northern Citizen"] = {
    TeamColor = BrickColor.new("Dark stone grey");
}

config["Ministry of Internal Affairs"] = {
    TeamColor = BrickColor.new("Black");
}

config["Southern Citizen"] = {
    TeamColor = BrickColor.new("Medium stone grey");
}

config["Tourist"] = {
    TeamColor = BrickColor.new("Ghost grey");
}

return config