---All the private Player attributes to be saved to file, with the default value
local config = {}

config.Badge5TIB = false
config.Badge10TIB = false
config.Badge25TIB = false
config.Badge50TIB = false
config.Badge100TIB = false
config.BadgeAlpha = false
config.BadgeDeicide = false
config.BadgeHomeowner = false
config.BadgeJackpot = false
config.BadgeMurderer = false
config.BadgeNorthGuard = false

config.BartenderExperience = 0
config.GuardsmanExperience = 0
config.MIAExperience = 0
config.SanitationExperience = 0

config.BartenderPaycheck = 0
config.GuardsmanPaycheck = 0
config.MIAPaycheck = 0
config.SanitationPaycheck = 0

config.CasinoLosses = 0
config.CasinoWelcomed = false
config.CasinoWinnings = 0
config.CasinoTime = 0

config.Stimulus = "1.1.2024."

return config