---All attributes of the Player to be saved to file, with their default value
local config = {}

config.BankBalance = 0
config.BankFrozen = false
config.PBNBAccount = false

config.Citizenship = "Tourist"
config.CitizenshipAt = 1711712958

config.DeathRow = false
config.Felon = false
config.HasRecord = false
config.Incarcerated = false
config.IncarceratedTo = 0

config.FreeSpins = 0

config.Muted = false

config.NameAssociations = "{}"

config.NGDischarged = false

config.NorthHDP = false
config.NorthLTC = false
config.NorthMGP = false

config.Occupation = "Unemployed"

config.PoliceDivision = ""
config.PoliceOffer = ""
config.PoliceRank = 0
config.PoliceSince = 1719096170

config.Pants = "IMMIGRANT_DEFAULT_PANTS"
config.Shirt = "IMMIGRANT_DEFAULT_SHIRT"

config.SearchWarrants = "[]"

return config