--Contains all contributors who worked on the game
local config = {}

config.Contributors = {
    {
        UserId = 17828104; --rogchamp
        Role = "Designer";
    };
    {
        UserId = 7019178; --Phalack
        Role = "Composer";
    };
    {
        UserId = 61286547; --ROGadilla
        Role = "3D Modeller";
    };
    {
        UserId = 657956829; --ColtDragoon
        Role = "3D Modeller";
    };
    {
        UserId = 92658764; --evaera
        Role = "EvLighting Module";
    };
    {
        UserId = 1659965; --buildthomas
        Role = "Rain Module";
    };
    {
        UserId = 112065603; --Submersibles
        Role = "3D Modeller";
    };
    {
        UserId = 18714963; --Anareloux
        Role = "Clothing Design";
    }
}

config.Developers = {
    {
        UserId = 156875176; --gitrog
        Role = "Lead Programmer";
    };
    {
        UserId = 700477025; --dogrog
        Role = "Builder";
    };
    {
        UserId = 1332822461; --alb
        Role = "Builder";
    };
}

return config